### ISSUE TITLE
Centrifuge:  height :337414 err: Could not find a reliable fee within the events data

### ISSUE THREAD

**Issue by LXHLeaner** [paritytech/substrate-api-sidecar#1002]
**Description**
node:  wss://fullnode.parachain.centrifuge.io
height: 337414

**ERR**

Could not find a reliable fee within the events data

**Code Location**

```
          // Check Event::Deposit events for the balances pallet.
		const depositEvents = this.findEvent(events, 'balances', Event.deposit);
		if (depositEvents.length > 0) {
			let sumOfFees = new BN(0);
			depositEvents.forEach(
				({ data }) =>
					(sumOfFees = sumOfFees.add(new BN(data[data.length - 1].toString())))
			);
			const adjustedPartialFee = tip ? tip.toBn().add(partialFee) : partialFee;
			// The difference between values is 00.00001% or less so they are alike.
			if (this.areFeesSimilar(sumOfFees, adjustedPartialFee)) {
				return {
					partialFee: sumOfFees.toString(),
				};
			}
		}
```

**TEST**
```
	private areFeesSimilar(eventBalance: BN, partialFee: BN): boolean {
		const diff = subIntegers(eventBalance, partialFee);

		console.log(eventBalance.toString())
		console.log(eventBalance.toString().length)

		console.log(diff.toString())
		console.log(diff.toString().length)

		console.log(partialFee.toString())
		console.log(partialFee.toString().length)

		return (
			eventBalance.toString().length - diff.toString().length > 5 &&
			eventBalance.toString().length === partialFee.toString().length
		);
	}
```

2022-08-01 20:28:25 info: 1223301467957835139883
2022-08-01 20:28:25 info: 22
2022-08-01 20:28:25 info: 1223301388865837346507
2022-08-01 20:28:25 info: 22
2022-08-01 20:28:25 info: 79091997793376
2022-08-01 20:28:25 info: 14

**Comment by jsdw** [comment]
Could you post the actual request and response you received back?

I'm pretty sure you'll still get a fee back as well as the error, but if you ask to get the fee from events, and no suitable events exist, then it has to call back to useing `queryFeeInfo` to obtain the fee, and so it's unable to do what you asked it to, hence the error.

**Comment by LXHLeaner** [comment]
So you know  how do you syncer the right fees about the centrifuge chain?

**Comment by TarikGul** [comment]
@LXHLeaner 

>  Can you give me a public node about the centriguge chain?

`wss://fullnode.parachain.centrifuge.io` <-> Is that what you are looking for?

> What is the thransfer crowdloanclaim-claim_reward meaning?
> What is the thransfer parachainsystem-set_validation_data meaning ?

I am almost positive the first crowdloan transfer event, is when an address has claimed their crowdloan rewards from an auction. Here is an [example](https://centrifuge.subscan.io/extrinsic/0x31434e8a789f8569fa07c707ac4268c0de98991a37035c6e13dc7608caa3a8c2?event=991298-10)

For the parachainSystem-set-validation-data its just setting validation data that was intrinsic to the block that was produced by the validators. 

>  If we have the api or others rpc to connect with the centrifuge chain?

Can you elaborate more on this I am not sure what it means. 

> if you can provide others document about the centrifuge chain,in addition to "https://docs.centrifuge.io/build/cent-chain/#introduction", It can make me know more about the characteristics of this chain；

This is centrifuge specific, we dont handle parachain documentation or parachain specific logic. that is seperate from the scope of sidecar unfortunately.

**Comment by TarikGul** [comment]
> So you know how do you syncer the right fees about the centrifuge chain? if not use this way, Whether or not have another way to syncer the true fees?

To expand on this, that just means the fee retrieved from queryInfo and and the fee within the events just don't match on a decimal length level. Dealing with every parachain is a little difficult, and we are currently expanding this solution to make sure we provide the same level of integrity for all of them. I can't guarantee for every parachain all the fees will be able to get fetched from the events as each chain may have their own nuances at this very moment.

**Comment by TarikGul** [comment]
Closing as this has become stale. Please feel free to open another issue if you have any more questions, but for future requests we don't deal with specific parachain logic, or support. We try to keep it to general support inheriting from substrate ad polkadot. 

That being said, in terms of fees it will all be solved with this PR: https://github.com/paritytech/substrate-api-sidecar/pull/1017. `feeByEvent` will be removed and fee's will go back to being accurate and correct for any chain that deals with fees with the same weight system as polkadot, and substrate. Which as far as I know is almost all if not all the chains at the moment.
