### ISSUE TITLE
[Feature] Full Validator list endpoint

### ISSUE THREAD

**Issue by TarikGul** [paritytech/substrate-api-sidecar#1005]
### **Description**

Should return a list of all the validators. This requires retrieving all the entries and mapping out the `AccountId` keys from storage. 

```typescript
const validators = await api.query.staking.validators.entries();
const keys = validators.forEach(([key]) => {
  console.log('key arguments:', key.args.map((k) => k.toHuman()));
});
```

Example JSON response from the endpoint:

```
{
    validators: [
        `162DmeD1MHpWQhv8NPz7zbUEfCyTfG4Tuqz7P7852KiY2wXz`,
        `13pYWKctR5s8vQuyZt3pxQXue4SRH9coyAS9S9z5HtogAnhs `,
        ...
    ]
}
```

**Comment by Imod7** [comment]
Another related endpoint to the one mentioned in this issue and maybe interesting to have is one that shows 
**"The list of nominators per validator"**

For example under an endpoint like :
`/pallets/staking/validators/validatorAddress`

This idea comes from seeing related questions in the Substrate Stack Exchange like the ones mentioned below : 
- [How to find all nominators of a validator?](https://substrate.stackexchange.com/questions/4056/polkadot-js-api-how-to-find-all-nominators-of-a-validator)
- [How to query the active nominators of X validator in past eras?](https://substrate.stackexchange.com/questions/2297/how-to-query-the-active-nominators-of-x-validator-in-past-eras)
- [How to get the nominators for a given validator address?](https://substrate.stackexchange.com/questions/4300/how-to-get-the-nominators-for-a-given-validator-address)
