### ISSUE TITLE
Return different code depending on the error

### ISSUE THREAD

**Issue by rootmout** [paritytech/substrate-api-sidecar#1032]
**Proposed Change or Idea**

When the API return an error, the error code is the same for two different types of errors. It could be an idea to have different error codes to be able to establish more efficiently the health status of the API.

If I query a discarded block:
```
rpc error (500): -32000: Client error: UnknownBlock: State already discarded for
BlockId::Hash(0x938b674497630f18a0e52bf39f9f1076a6a04f20d59535d1e8401bc1f60a2dae)
```
If I've an internal error (like what I've actually https://github.com/paritytech/substrate-api-sidecar/issues/898#issuecomment-1231744541):
```
rpc error (500): Unable to decode storage session.validators:: createType(PalletDemocracyEvent)::
Unable to create Enum via index 165, in Proposed, Tabled, ExternalTabled, Started, Passed, NotPassed,
Cancelled, Executed, Delegated, Undelegated, Vetoed, PreimageNoted, PreimageUsed, PreimageInvalid,
PreimageMissing, PreimageReaped, Blacklisted, Voted, Seconded
```
both return `500` error

**Alternatives**

Return different 5XX error

**Comment by TarikGul** [comment]
This all being said, we had a conversation about this with the team, and agree that some kind of enhancement with the messages will be a great boost for Sidecar. This is something that will definitely be looked into for Sidecar v2 as we design the rework.

**Comment by TarikGul** [comment]
Closing as this is getting stale, and a non issue for the current iteration of sidecar.
