### ISSUE TITLE
Different response types according to network "blocks/head"

### ISSUE THREAD

**Issue by FurkanAydnn** [paritytech/substrate-api-sidecar#1063]
Hi. 
I'm using latest version of substrate-api in docker. 

- For live-public-network
  -  `docker run --rm -it -e SAS_SUBSTRATE_WS_URL=wss://rpc.polkadot.io -p 8080:8080 substrate-api-sidecar`
  - ![image](https://user-images.githubusercontent.com/46317886/191266707-96aca735-4e27-45d3-986d-407f12afde57.png)
  - ![image](https://user-images.githubusercontent.com/46317886/191266560-b108b055-83a5-4d93-94d9-dd10ac0f3afe.png)

- For westend-public-network
  - Run command: `docker run --rm -it -e SAS_SUBSTRATE_WS_URL=wss://westend-rpc.polkadot.io -p 8080:8080 substrate-api-sidecar`
  - ![image](https://user-images.githubusercontent.com/46317886/191266034-5e805221-ee5a-4952-b21f-da9d7016f237.png)
  - ![image](https://user-images.githubusercontent.com/46317886/191266316-cd95c34a-ee35-4cc4-a89e-1aad44c75a12.png)

Like the screenshots above, There are differences (marked with red square) between responses.
What could be the reason for this difference?

**Comment by niklasad1** [comment]
Hey @FurkanAydnn 

This reason is that the weight representation was changed in `v0.9.29` and polkadot is lagging two releases behind westend.
That's why you get different responses on the networks.

**Comment by FurkanAydnn** [comment]
Thanks for quick response 👍
