### ISSUE TITLE
Feature: Support for Nomination Pools

### ISSUE THREAD

**Issue by TarikGul** [paritytech/substrate-api-sidecar#1064]
We should consider supporting an endpoint for nomination pools. 

## `/pallets/nominationPools/:poolId`

Query Params: 
- at: (Optional) blockId or hash (Note: it is important to use `api.at` for any queries (Not RPC methods), when we want to query at a specific blockHash, we call this the historicApi in Sidecar and you can reference other controllers and services for exampels).
- metadata: (Optional) This will be optional for the user and should be a boolean. So either true or false, and will deefault to false

Response: 
```
{
    at: {
        hash: string,
        height: string
    },
    bondedPool: {
        points: int as string,
        state: string,
        memberCounter: int as string,
        roles: {
            depositor: string,
            root: string,
            nominator: string,
            stateToggler: string
        }
    },
    rewardPool: {
        lastRecordedRewardCounter: string,
        lastRecordedTotalPayouts: string,
        totalRewardsClaimed: string
    },
    metadata: string
}
```

Resources:
[NominationPools queries in polkadot-js](https://github.com/polkadot-js/api/blob/master/packages/api-augment/src/kusama/query.ts#L802-L893)
[Substrate nomination pools storage types](https://github.com/paritytech/substrate/blob/master/frame/nomination-pools/src/lib.rs#L1234-L1299)

## `/pallets/nominationPools/info`

Query Params: 
- at: blockId or hash

Response
```
{
    at: {
        hash: string,
        height: string
    },
    counterForBondedPools: string,
    counterForMetadata: string,
    counterForPoolMembers: string,
    counterForReversePoolIdLookup: string,
    counterForRewardPools: string,
    counterForSubPoolsStorage: string,
    lastPoolId: string,
    maxPoolMembers: string,
    maxPoolMembersPerPool: string,
    maxPools: string,
    minCreateBond: string,
    minJoinBond: string,
}
```

**Comment by TarikGul** [comment]
@kianenigma Any thoughts, or if there is anything extra you would like to see let us know.

**Comment by LXHLeaner** [comment]
How  to get the nominator rewords? can you give me a example?
