### ISSUE TITLE
build a polkadot staking

### ISSUE THREAD

**Issue by LXHLeaner** [paritytech/substrate-api-sidecar#1066]
how i  can use substrate-api-sidecar  to build a staking transcation?

**Comment by TarikGul** [comment]
Sidecar does not provide a way to build transactions. You can only submit them using `/transaction` to submit transactions. There is no current roadmap to add that feature in currently either. closing.

**Comment by LXHLeaner** [comment]
so ,what rpc i can use about staking ?

**Comment by TarikGul** [comment]
> so ,you means that you can not support staking

No it means we do not support constructing transactions server side. You will need to construct them yourself. You can use libraries such as [txwrapper-core](https://github.com/paritytech/txwrapper-core) to construct the transaction then broadcast it using sidecar. There is no RPC method to construct a staking transaction.
