### ISSUE TITLE
Bad gateway error with sidecar

### ISSUE THREAD

**Issue by sankararaok** [paritytech/substrate-api-sidecar#1121]
**Description**

I am getting Bad gateway error while trying the sidecar APIs

**Steps to Reproduce**

Earlier i have side car node with parity/substrate-api-sidecar:v12.4.3 version and my main polka dot node is parity/polkadot:v0.9.27.
I do not have issue .
I have upgraded my Polkadot node to parity/polkadot:v0.9.30 and my side car to parity/substrate-api-sidecar:v14.0.1, from then onwards i am getting "502 Bad Gateway"  error i tried multiple version of side car like v13.0.0 , v13.1.0 but no use , getting same.

Please guide me on this

**Comment by Imod7** [comment]
Hello @sankararaok 
Could you check your `docker-compose.yml` to see how the environment variable for the ws address is set ? 

As mentioned in this [comment](https://github.com/paritytech/substrate-api-sidecar/issues/1065#issuecomment-1257085134) on Issue 1065, this changed in [Sidecar v13.0.0](https://github.com/paritytech/substrate-api-sidecar/releases/tag/v13.0.0) from `SAS_SUBSTRATE_WS_URL`  to `SAS_SUBSTRATE_URL`.

**Comment by TarikGul** [comment]
Hey @sankararaok, are you still experiencing an issue with this?

**Comment by TarikGul** [comment]
Going to close this because it's becoming stale, please reopen, or file a new issue if you are still experiencing issues.
