### ISSUE TITLE
Please publish a subset-api-sidecar version compatible with Polkadot v9310

### ISSUE THREAD

**Issue by vae520283995** [paritytech/substrate-api-sidecar#1128]
https://github.com/paritytech/polkadot/releases/tag/v0.9.31 
Polkadot v9310 Published

**Comment by vae520283995** [comment]
```
{"code":500,"message":"1: Unable to query dispatch info.: Failed to decode return value of TransactionPaymentApi_query_info","stack":"RpcError: 1: Unable to query dispatch info.: Failed to decode return value of TransactionPaymentApi_query_info\n    at checkError (/usr/src/app/node_modules/@polkadot/rpc-provider/cjs/coder/index.js:30:11)\n    at RpcCoder.decodeResponse (/usr/src/app/node_modules/@polkadot/rpc-provider/cjs/coder/index.js:45:5)\n    at WsProvider.value (/usr/src/app/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:246:90)\n    at W3CWebSocket.value [as onmessage] (/usr/src/app/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:229:153)\n    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/usr/src/app/node_modules/yaeti/lib/EventTarget.js:107:17)\n    at W3CWebSocket.onMessage (/usr/src/app/node_modules/websocket/lib/W3CWebSocket.js:234:14)\n    at WebSocketConnection.<anonymous> (/usr/src/app/node_modules/websocket/lib/W3CWebSocket.js:205:19)\n    at WebSocketConnection.emit (node:events:527:28)\n    at WebSocketConnection.processFrame (/usr/src/app/node_modules/websocket/lib/WebSocketConnection.js:554:26)\n    at /usr/src/app/node_modules/websocket/lib/WebSocketConnection.js:323:40","level":"error"}
```

**Comment by vae520283995** [comment]
@TarikGul please help

**Comment by niklasad1** [comment]
Hey @vae520283995 have you tried https://github.com/paritytech/substrate-api-sidecar/releases/tag/v14.1.0?

**Comment by vae520283995** [comment]
> Hey @vae520283995 have you tried https://github.com/paritytech/substrate-api-sidecar/releases/tag/v14.1.0?

Yes, I just use v14.1.0

**Comment by niklasad1** [comment]
//cc @marshacb

**Comment by haruki515** [comment]
Hi guys,
It appears that store_call has been removed in polkadot 0.9.31, is this compatible with v14.1.0?
https://github.com/paritytech/substrate/pull/12072

**Comment by niklasad1** [comment]
@vae520283995 

I think you are suffering an unintended breaking change in the runtime API `payment_queryInfo` in polkadot v0.9.31 which was fixed by https://github.com/paritytech/substrate/pull/12633

That fix will be available in polkadot v0.9.32, can you test with that version please?

**Comment by vae520283995** [comment]
> That fix will be available in polkadot v0.9.32, can you test with that version please?

Sure, no problem

**Comment by lvccomputer** [comment]
I can't get fees on v14.1.0?
`{
    "code": 500,
    "error": "Unable to fetch fee info",
    "transaction": "0x2d028400fc6c8f07a77d2e57730832130174b2bc06a8ff2b6d632c4ccad9ca7c0a8e310a01c270ef63690b27fc68d3bbf901ea5f186da20f1db50b50c02a3e5b1d3cda5f0adab8aba2811c74fcb14aed2116a055fddec9cb3b85a0283ca2de69664f7f3180b5023c00040000fc6c8f07a77d2e57730832130174b2bc06a8ff2b6d632c4ccad9ca7c0a8e310a00",
    "cause": "createType(RuntimeDispatchInfo):: Struct: failed on weight: u64:: Unable to construct number from multi-key object",
    "stack": "Error: createType(RuntimeDispatchInfo):: Struct: failed on weight: u64:: Unable to construct number from multi-key object\n    at createTypeUnsafe (/usr/src/app/node_modules/@polkadot/types-create/cjs/create/type.js:67:18)\n    at TypeRegistry.createTypeUnsafe (/usr/src/app/node_modules/@polkadot/types/cjs/create/registry.js:295:46)\n    at RpcCore._formatOutput (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:381:21)\n    at RpcCore._formatResult (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:209:27)\n    at callWithRegistry (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:235:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
}`

**Comment by vae520283995** [comment]
> I can't get fees on v14.1.0? `{ "code": 500, "error": "Unable to fetch fee info", "transaction": "0x2d028400fc6c8f07a77d2e57730832130174b2bc06a8ff2b6d632c4ccad9ca7c0a8e310a01c270ef63690b27fc68d3bbf901ea5f186da20f1db50b50c02a3e5b1d3cda5f0adab8aba2811c74fcb14aed2116a055fddec9cb3b85a0283ca2de69664f7f3180b5023c00040000fc6c8f07a77d2e57730832130174b2bc06a8ff2b6d632c4ccad9ca7c0a8e310a00", "cause": "createType(RuntimeDispatchInfo):: Struct: failed on weight: u64:: Unable to construct number from multi-key object", "stack": "Error: createType(RuntimeDispatchInfo):: Struct: failed on weight: u64:: Unable to construct number from multi-key object\n at createTypeUnsafe (/usr/src/app/node_modules/@polkadot/types-create/cjs/create/type.js:67:18)\n at TypeRegistry.createTypeUnsafe (/usr/src/app/node_modules/@polkadot/types/cjs/create/registry.js:295:46)\n at RpcCore._formatOutput (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:381:21)\n at RpcCore._formatResult (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:209:27)\n at callWithRegistry (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:235:19)\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (node:internal/process/task_queues:96:5)" }`

@lvccomputer Which version of Polkadot node do you use?

**Comment by vae520283995** [comment]
Use [polkadot v0.9.32](https://github.com/paritytech/polkadot/releases/tag/v0.9.32)  The problem has been fixed
