### ISSUE TITLE
Error: Method: Post, Receive a fee estimate for a transaction

### ISSUE THREAD

**Issue by trinhvanvinh** [paritytech/substrate-api-sidecar#1132]
**Description**

"code": 500,
    "error": "Unable to fetch fee info",
"cause": "createType(RuntimeDispatchInfo):: Struct: failed on weight: u64:: Unable to construct number from multi-key object"

We have a above  problem at version current 14.1.0. Please help me resolve it. Thank you so much.

**Comment by vae520283995** [comment]
@trinhvanvinh Which version of Polkadot node do you use?

**Comment by TarikGul** [comment]
Hey @trinhvanvinh, are you still having this issue. If so can you provide me with the following info:

What node you are querying, a reproducible endpoint, and the runtime version you are querying?

**Comment by TarikGul** [comment]
Due to being stale, I am going to close this issue. If this comes up again, or you would like to rehash this issue please feel free to open or open a new issue.
