### ISSUE TITLE
GET /blocks/15426018  no results 500 error

### ISSUE THREAD

**Issue by xiaochisAmber** [paritytech/substrate-api-sidecar#1138]
I tried both my own deployed nodes and third-party nodes, but could not get the results

 curl localhost:8080/blocks/15426018
{"code":500,"message":"createType(RuntimeDispatchInfo):: Struct: failed on weight: {\"refTime\":\"Lookup9\",\"proofSize\":\"Lookup9\"}:: Struct: Cannot decode value 27549795 (typeof number), expected an input object, map or array","stack":"Error: createType(RuntimeDispatchInfo):: Struct: failed on weight: {\"refTime\":\"Lookup9\",\"proofSize\":\"Lookup9\"}:: Struct: Cannot decode value 27549795 (typeof number), expected an input object, map or array\n    at createTypeUnsafe (/usr/src/app/node_modules/@polkadot/types-create/cjs/create/type.js:67:18)\n    at TypeRegistry.createTypeUnsafe (/usr/src/app/node_modules/@polkadot/types/cjs/create/registry.js:295:46)\n    at RpcCore._formatOutput (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:381:21)\n    at RpcCore._formatResult (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:209:27)\n    at callWithRegistry (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:235:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","level":"error"}

------------

curl -X GET \
> https://svc.blockdaemon.com/kusama/mainnet/native/blocks/15426018 \
> -H 'Authorization: Bearer '*****'
{
    "status": 500,
    "code": "500",
    "title": "Internal Server Error",
    "detail": "https://blockdaemon.com/documentation/"

**Comment by TarikGul** [comment]
Hey @xiaochisAmber, thanks for reporting this issue. I was able to reproduce this on Kusama and looking into solutions right now.

**Comment by vae520283995** [comment]
@TarikGul  Hello, is it normal that the weight structure has changed after the update
before
```
"events": [
                {
                    "method": {
                        "pallet": "system",
                        "method": "ExtrinsicSuccess"
                    },
                    "data": [
                        {
                            "weight": "245453000",
                            "class": "Mandatory",
                            "paysFee": "Yes"
                        }
                    ]
                }
            ]
```
after
```
{
                    "method": {
                        "pallet": "system",
                        "method": "ExtrinsicSuccess"
                    },
                    "data": [
                        {
                            "weight": {
                                "refTime": "595159121468",
                                "proofSize": "0"
                            },
                            "class": "Mandatory",
                            "paysFee": "Yes"
                        }
                    ]
                }
```

**Comment by IkerAlus** [comment]
@vae520283995 Yes, in [Polkadot Release v0.9.31](https://github.com/paritytech/polkadot/releases/tag/v0.9.31) a storage size (`profSize`) component to weights. You can read more about this change in [the PR](https://github.com/paritytech/substrate/pull/12277).
