### ISSUE TITLE
ksm Unable to fetch Events, cannot confirm extrinsic status. Check pruning settings on the node

### ISSUE THREAD

**Issue by charleslei01** [paritytech/substrate-api-sidecar#1143]
curl http://127.0.0.1:8080/blocks/15435591

Partial parameters of my node configuration： `--pruning=archive`

When I execute the 👆🏻 command in the node,I got a question，

**Unable to fetch Events, cannot confirm extrinsic status. Check pruning settings on the node**
<img width="1597" alt="image" src="https://user-images.githubusercontent.com/90607216/203291309-bcf54145-6889-4713-b2dd-b6115c0c7323.png">

My node has been running stably for half a year, and this problem started about yesterday, exactly from height **15426016**. I have two KSM nodes with different environments in this situation, how can I solve this problem?

**Comment by TarikGul** [comment]
Hey @charleslei01, what version of Sidecar are you using? On the latest version v14.1.2 I cant reproduce this.

**Comment by charleslei01** [comment]
Hey @TarikGul , My ksm version is **v0.9.29**  sidecar is **v14.0.0** I upgrade both to the latest version

**Comment by charleslei01** [comment]
**v14.1.2 run error**

# node main.js
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'node:perf_hooks'
Require stack:
- /usr/bin/substrate-api-sidecar-14.1.2/node_modules/@substrate/smoldot-light/dist/cjs/index-nodejs.js
- /usr/bin/substrate-api-sidecar-14.1.2/node_modules/@substrate/connect/dist/cjs/connector/smoldot-light.js
- /usr/bin/substrate-api-sidecar-14.1.2/node_modules/@substrate/connect/dist/cjs/connector/index.js
- /usr/bin/substrate-api-sidecar-14.1.2/node_modules/@substrate/connect/dist/cjs/index.js
- /usr/bin/substrate-api-sidecar-14.1.2/node_modules/@polkadot/rpc-provider/cjs/substrate-connect/index.js
- /usr/bin/substrate-api-sidecar-14.1.2/node_modules/@polkadot/rpc-provider/cjs/bundle.js
- /usr/bin/substrate-api-sidecar-14.1.2/node_modules/@polkadot/rpc-provider/cjs/index.js
- /usr/bin/substrate-api-sidecar-14.1.2/node_modules/@polkadot/api/cjs/bundle.js
- /usr/bin/substrate-api-sidecar-14.1.2/node_modules/@polkadot/api/cjs/index.js
- /usr/bin/substrate-api-sidecar-14.1.2/build/src/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/bin/substrate-api-sidecar-14.1.2/node_modules/@substrate/smoldot-light/dist/cjs/index-nodejs.js:24:27)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/bin/substrate-api-sidecar-14.1.2/node_modules/@substrate/smoldot-light/dist/cjs/index-nodejs.js',
    '/usr/bin/substrate-api-sidecar-14.1.2/node_modules/@substrate/connect/dist/cjs/connector/smoldot-light.js',
    '/usr/bin/substrate-api-sidecar-14.1.2/node_modules/@substrate/connect/dist/cjs/connector/index.js',
    '/usr/bin/substrate-api-sidecar-14.1.2/node_modules/@substrate/connect/dist/cjs/index.js',
    '/usr/bin/substrate-api-sidecar-14.1.2/node_modules/@polkadot/rpc-provider/cjs/substrate-connect/index.js',
    '/usr/bin/substrate-api-sidecar-14.1.2/node_modules/@polkadot/rpc-provider/cjs/bundle.js',
    '/usr/bin/substrate-api-sidecar-14.1.2/node_modules/@polkadot/rpc-provider/cjs/index.js',
    '/usr/bin/substrate-api-sidecar-14.1.2/node_modules/@polkadot/api/cjs/bundle.js',
    '/usr/bin/substrate-api-sidecar-14.1.2/node_modules/@polkadot/api/cjs/index.js',
    '/usr/bin/substrate-api-sidecar-14.1.2/build/src/main.js'
  ]
}

**Comment by TarikGul** [comment]
I think the above error is in regards to your node.js version. What version of node.js are you using?

**Comment by TarikGul** [comment]
Were you able to get this resolved?

**Comment by TarikGul** [comment]
This issue is now stale, please feel free to reopen or file a new issue if you have any further info or questions.
