### ISSUE TITLE
When using this interface "/blocks/:number", this code is returned with a 500 error

### ISSUE THREAD

**Issue by LXHLeaner** [paritytech/substrate-api-sidecar#1165]
**Description**
When using this interface "/blocks/:number of the chain is Karura" , this code is returned with a 500 error，How to solve it ?

**Information**
Chain: Karura
let WS_URL = 'wss://karura-rpc-3.aca-api.network/ws';

**ERR:500**
{
    "code": 500,
    "message": "createType(RuntimeDispatchInfoV1):: Struct: failed on weight: u64:: Unable to construct number from multi-key object",
    "stack": "Error: createType(RuntimeDispatchInfoV1):: Struct: failed on weight: u64:: Unable to construct number from multi-key object\n    at createTypeUnsafe (/Users/lc/Documents/TestGoProject/src/karura/substrate-api-sidecar/node_modules/@polkadot/types-create/cjs/create/type.js:67:18)\n    at TypeRegistry.createTypeUnsafe (/Users/lc/Documents/TestGoProject/src/karura/substrate-api-sidecar/node_modules/@polkadot/types/cjs/create/registry.js:295:46)\n    at RpcCore._formatOutput (/Users/lc/Documents/TestGoProject/src/karura/substrate-api-sidecar/node_modules/@polkadot/rpc-core/cjs/bundle.js:381:21)\n    at RpcCore._formatResult (/Users/lc/Documents/TestGoProject/src/karura/substrate-api-sidecar/node_modules/@polkadot/rpc-core/cjs/bundle.js:209:27)\n    at callWithRegistry (/Users/lc/Documents/TestGoProject/src/karura/substrate-api-sidecar/node_modules/@polkadot/rpc-core/cjs/bundle.js:235:19)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "level": "error"
}

**Comment by TarikGul** [comment]
Can you kindly provide a block number to associate the bug with?

**Comment by xlc** [comment]
block `2537106` on Acala have this issue as well

**Comment by xlc** [comment]
The issue is that on Karura / Acala, we have performed a runtime upgrade and the new runtime is using WeightV2, which indirectly changes the return type of the `payment_queryInfo` because `RuntimeDispatchInfo` includes a `Weight` field and thus incompatibility. The RPC return type is hardcoded on client side and it is unable to use metadata to infer the correct weight type and therefore failed to decode the return type.

**Comment by TarikGul** [comment]
> block `2537106` on Acala have this issue as well

Thanks for the block number. I was able to reproduce it, and will jump on this right away.

**Comment by xlc** [comment]
According to Jaco, we need to upgrade our node to include this https://github.com/paritytech/substrate/pull/12633 
Will do the upgrade on Acala and see if it resolves this issue

**Comment by TarikGul** [comment]
> According to Jaco, we need to upgrade our node to include this [paritytech/substrate#12633](https://github.com/paritytech/substrate/pull/12633) Will do the upgrade on Acala and see if it resolves this issue

Thanks for being on top of this, @IkerAlus had let me know that it seemed to be a PR missing in the runtime upgrade as well via Jaco, glad to know it's going to be solved!

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/design-a-friendly-easy-updatable-iterable-system/1674/5
