### ISSUE TITLE
Add endpoint for generic storage queries

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/substrate-api-sidecar#117]
Add an endpoint that enables querying any storage item from any pallet. It will need to handle all types of storage items, like values, maps, and double maps. It will also need to handle a block ID input for querying that item at that block ID.

There are a lot of ways to implement this, but perhaps something like:
- `/storage/<pallet>/<item>?key1=abc&key2=def`

**Comment by danforbes** [comment]
A more RESTful way to represent this may be `/pallets/{palletId}/storage/{storageItemId}?key1=abc&key2=def`. This expresses the idea that the storage "belongs to" the pallet as opposed to the pallet "belonging to" the storage.

**Comment by joepetrowski** [comment]
> This expresses the idea that the storage "belongs to" the pallet as opposed to the pallet "belonging to" the storage.

Depends on your point of view. Within FRAME, yes. But within the state trie, all keys for an entire pallet could be under a single node (a child trie).

Anyway, not married to anything yet.

**Comment by emostov** [comment]
Closed by #278
