### ISSUE TITLE
Find extrinsic by hash

### ISSUE THREAD

**Issue by jqriyv** [paritytech/substrate-api-sidecar#1172]
If I have extrinsic hash just only, i don't get the extrinsic detail.

**Comment by TarikGul** [comment]
Extrinisic hashes in substrate are not unique therefore you can't find a extrinsic just by it's hash, you would need the hash and the `Timepoint` (It's extrinsicIndex). That means you need to know the block in which the transaction took place, and the extrinsicIndex as well as it's hash.

**Comment by TarikGul** [comment]
Closing due to getting stale, feel free to reopen or file a new issue if you need further help.
