### ISSUE TITLE
Provided docs return Error 404

### ISSUE THREAD

**Issue by kopeboy** [paritytech/substrate-api-sidecar#1190]
**Description**

Is the API active? I just tested some GET requests from https://paritytech.github.io/substrate-api-sidecar/dist/ and they all returned 404

**Steps to Reproduce**

Head over to https://paritytech.github.io/substrate-api-sidecar/dist/ and "Try it out"

**Expected vs. Actual Behavior**

I understand one should have a node endpoint to query, but at least for testing purposes and providing complete documentation, the provided link should just work.

**Comment by TarikGul** [comment]
Hey, thanks for bringing this up. It's been on my backlog but hasn't been a priority so I kind of forgot about it. Im happy to give it the TLC it needs today. My idea at first was to just disable the `try it out` feature, but I think given the public endpoints of sidecar we have I can just route it to there.

**Comment by TarikGul** [comment]
For now we are removing the `try it out` until a proper solution is in place. My first run through there were some issue with CORS, so whether we want to do a proxy server, or serve the docs directly from the api im not totally sure yet.
