### ISSUE TITLE
Transaction fee estimate returns error 

### ISSUE THREAD

**Issue by PizBernina** [paritytech/substrate-api-sidecar#1218]
**Description**

Mainnet DOT & KSM
For any sidecar version newer than 14.2.1, both dot and ksm sidecars return an error when using the following endpoint
`<node>/transaction/fee-estimate` with an unsigned transaction.

**Steps to Reproduce**

1. Pick a serialized unsigned transaction
2. Post it to https://kusama-public-sidecar.parity-chains.parity.io/transaction/fee-estimate

**Expected vs. Actual Behavior**

I expect it to return the fee estimate.

It actually returns this 
`ExceptionMessage: {\"code\":500,\"error\":\"Unable to fetch fee info\",\"transaction\":\"<unsigned-tx-hash>\",\"cause\":\"createType(Extrinsic):: createType(ExtrinsicV4):: createType(Call):: findMetaCall: Unable to find Call with index [0, 86]/[0,86]\",\"stack\":\"Error: createType(Extrinsic):: createType(ExtrinsicV4):: createType(Call):: findMetaCall: Unable to find Call with index [0, 86]/[0,86]\\n    at createTypeUnsafe (/usr/local/substrate-api-sidecar-14.3.0/node_modules/@polkadot/types-create/cjs/create/type.js:71:18)\\n    at TypeRegistry.createType (/usr/local/substrate-api-sidecar-14.3.0/node_modules/@polkadot/types/cjs/create/registry.js:288:46)\\n    at TransactionFeeEstimateService.fetchTransactionFeeEstimate (/usr/local/substrate-api-sidecar-14.3.0/build/src/services/transaction/TransactionFeeEstimateService.js:34:42)\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\\n    at async TransactionFeeEstimateController.txFeeEstimate (/usr/local/substrate-api-sidecar-14.3.0/build/src/controllers/transaction/TransactionFeeEstimateController.js:66:65)\\n    at async /usr/local/substrate-api-sidecar-14.3.0/build/src/controllers/AbstractController.js:226:9`

**Comment by IkerAlus** [comment]
I agree the error returned by Sidecar should be more 

but the expected behaviour should not be a fee estimation signed [unsigned transactions](https://docs.substrate.io/fundamentals/transaction-types/#unsigned-transactions) do not pay fees.

Also, `/transaction/fee-estimate` endpoint needs the serialized transaction as input, not the transaction hash.

**Comment by PizBernina** [comment]
> Perhaps the error returned by Sidecar could be more informative when the input is an unsigned transaction... but the expected behaviour should not be a fee estimation since [unsigned transactions](https://docs.substrate.io/fundamentals/transaction-types/#unsigned-transactions) do not pay fees.
> 
> Also, `/transaction/fee-estimate` endpoint needs the serialized transaction as input, not the transaction hash.

Hm, but it works with sidecar versions <= 14.2.1.
Btw same error is returned when trying it with a signed tx.

Indeed, it's not a hash but serialized unsigned tx. I corrected it.

**Comment by PizBernina** [comment]
hi @IkerAlus any update on this one?

**Comment by Imod7** [comment]
Hello @PizBernina 
I was trying to replicate your use case on my end and reproduce the error you get but unfortunately I was unable to. For me it is working as expected. Maybe you could provide the exact input you give, code snippet/script that you are using to generate the serialized unsigned tx or more details on your setup so I can try again by reproducing as close as possible what you are attempting to do ?

**Comment by PizBernina** [comment]
> Hello @PizBernina I was trying to replicate your use case on my end and reproduce the error you get but unfortunately I was unable to. For me it is working as expected. Maybe you could provide the exact input you give, code snippet/script that you are using to generate the serialized unsigned tx or more details on your setup so I can try again by reproducing as close as possible what you are attempting to do ?

Hi, sure:

```

import requests 
import json

url = "https://kusama-public-sidecar.parity-chains.parity.io/transaction/fee-estimate"
payload = json.dumps({"tx":0x550284005665ef9894f68738853586822941e372b30a1e621bda3f5698effd4a5e581f31000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040208af2f0403005665ef9894f68738853586822941e372b30a1e621bda3f5698effd4a5e581f31137cf0010c343237a8"})
headers = {'Content-Type': 'application/json'}
response = requests.request("POST", url, headers=headers, data=payload)
print(response.text)

```

**Comment by IkerAlus** [comment]
hey @PizBernina 

is the issue present with every serialized unsigned transaction or only with the one provided above? How did you generate the transaction above?

For sure `0x550284005665ef9894f68738853586822941e372b30a1e621bda3f5698effd4a5e581f31000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040208af2f0403005665ef9894f68738853586822941e372b30a1e621bda3f5698effd4a5e581f31137cf0010c343237a8 ` does not look like a byte array representing a extrinsic in the Polkadot/Kusama ecosystems.

**Comment by PizBernina** [comment]
thanks for your patience @IkerAlus @Imod7. Got feedback from the team. So, it seems that if we sign the transaction it works. We decided to just sign them from now on and not use the endpoint with unsigned transactions ones anymore.
