### ISSUE TITLE
feat: allow configure exress server

### ISSUE THREAD

**Issue by tetz-akaneya** [paritytech/substrate-api-sidecar#1231]
**Proposed Change or Idea**

Currently, we have problem with short express keepAliveTimeout default value which is 5 seconds.
The problem is detailed in this [blog](https://shuheikagawa.com/blog/2019/04/25/keep-alive-timeout/).

It should be possible to pass config to express.

**Alternatives**

N/A

**Additional Information**

N/A

**Comment by TarikGul** [comment]
Hey @tetz-akaneya,

Im okay with making this configurable, it would most likely be a env var called `SAS_KEEP_ALIVE_TIMEOUT`, and if configured we would make the header timeout by default 5 seconds more.

**Comment by tetz-akaneya** [comment]
Hi @TarikGul , SAS_KEEP_ALIVE_TIMEOUT is great.
Following TarikGul idea, the code would look like this.

```
if (process.env.SAS_KEEP_ALIVE_TIMEOUT) {
  server.keepAliveTimeout = +SAS_KEEP_ALIVE_TIMEOUT
  server.headersTimeout = +SAS_KEEP_ALIVE_TIMEOUT + 5000
}
```

**Comment by TarikGul** [comment]
So not exactly, in a traditional express layout yes, but not in sidecar. I will push the PR later today that add the env vars, but we use a config manager for a more "enterprise" style approach.

**Comment by tetz-akaneya** [comment]
hey, thanks for the PR!
