### ISSUE TITLE
A question about the parachain equilibrium 

### ISSUE THREAD

**Issue by LXHLeaner** [paritytech/substrate-api-sidecar#1250]
[Question]

Do we support the Parachain equilibrium ?

**Comment by TarikGul** [comment]
Yes, out of the box we support all substrate based chains. But that being said, if a chain wants specialized configs (support), there needs to be a `chains-config` for them. Which Equilibrium doesn't have one.

Here is the [directory](https://github.com/paritytech/substrate-api-sidecar/tree/master/src/chains-config) to check through chains that have `configs` for sidecar.

**Comment by TarikGul** [comment]
Closing as this is stale, and answered. Feel free to open another issue with a question.
