### ISSUE TITLE
replace tsc-watch with ts-node-dev

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate-api-sidecar#1306]
ts-node-dev offers much better DX. only time to perform build is for release, otherwise developers should never need to build ts to js locally.

**Comment by TarikGul** [comment]
Sounds like an easy QOL improvement, i'll look to get this done soon.

**Comment by TarikGul** [comment]
We do have `tsc-watch` for `yarn dev` which is just a hot reload, but I'll need to look into `ts-node-dev` and see how it works.

**Comment by TarikGul** [comment]
Awesome, thanks for the suggestion. I really like the change, PR is up to swap out tsc-watch.
