### ISSUE TITLE
Feature: Add endpoint to query Asset Conversion pallet storage

### ISSUE THREAD

**Issue by IkerAlus** [paritytech/substrate-api-sidecar#1308]
API Sidecar should have endpoints to query directly the storage of the new [Asset Conversion pallet](https://github.com/paritytech/substrate/tree/master/frame/asset-conversion) on Asset Hub. The proposed idea is to add two new endpoints:

- One to query for the next available pool ID, returning an integer.

- A second endpoint to retrieve the list of existing liquidity pools. The suggestion here to simply return the whole list of existing pools and do not allow query by asset ID (multilocation) due to the complex UX in a `GET` request.

**Additional Information**

Screenshot of the state queries exposed by the Asset Conversion pallet from Polkadot.js APPs:

<img width="1348" alt="Screenshot 2023-07-13 at 17 26 12" src="https://github.com/paritytech/substrate-api-sidecar/assets/34474035/9fcbcfc4-7e40-4385-ab68-6fa4974e5733">

**Comment by TarikGul** [comment]
The endpoints should be:

`/pallets/asset-conversion/next-available-id`
`/pallets/asset-conversion/liquidity-pools`

**Comment by bee344** [comment]
Closed by PR #1324 . Further implementations are tracked by Issue #1322 .
