### ISSUE TITLE
docker-compose.yml no longer works with v1.0.0 of polkadot node

### ISSUE THREAD

**Issue by benxiao** [paritytech/substrate-api-sidecar#1316]
**Description**

it seems  that --unsafe-ws-external has been removed from v1.0.0. and simply use --ws-external doesn't work.

**Steps to Reproduce**
docker-compose up -d

**Expected vs. Actual Behavior**

![image](https://github.com/paritytech/substrate-api-sidecar/assets/10908495/2ed06e5f-d95f-4f60-84e9-efbd184a83de)

[A clear description of what you expected to happen and what actually happened.]

**Comment by TarikGul** [comment]
Thanks for reporting this issue I will have checked out tomorrow.

**Comment by benxiao** [comment]
according to https://github.com/paritytech/polkadot/releases/tag/v0.9.43, it was replaced with `--unsafe-rpc-external.`

**Comment by TarikGul** [comment]
@benxiao Thanks for the PR, closing as this is resolved.
