### ISSUE TITLE
feat: add asset-conversion endpoint to Polkadot and Kusama's Asset Hub

### ISSUE THREAD

**Issue by bee344** [paritytech/substrate-api-sidecar#1322]
**Proposed Change or Idea**

Add `asset-conversion` endpoints for `Asset-Hub-Polkadot` and `Asset-Hub-Kusama` once it becomes available on the live chain.

**Additional Information**

Currently the `Pallet Asset Conversion` is only available on `Asset Hub Westend`, but this is a reminder to add the endpoint for the other `Asset-Hub-*` when it's available.

**Coverage**

- [x] Westend Asset Hub
- [x] Kusama Asset Hub
- [ ] Polkadot Asset Hub

**Comment by IkerAlus** [comment]
@bee344 Polkadot AH is also ready for this one
