### ISSUE TITLE
Sidecar feee request issue

### ISSUE THREAD

**Issue by Seel555** [paritytech/substrate-api-sidecar#1462]
Hello, exception during /transaction/fee-estimate request:

{
    "code": 400,
    "error": "Unable to fetch fee info",
    "transaction": "0x310284007e0c40daa86b608f9f3c26000be523682ac13eaedd685ddb67dbc2f5ecd4fa740130cccbf73901f888d4ff8bcb1a8c41e7328e1c108b6000b44d7160bff531d72f42578720b71e13246ab87b19b8ca099d37f0b01c57f66b5822bdd41b1e74ef8b15000904000504007e0c40daa86b608f9f3c26000be523682ac13eaedd685ddb67dbc2f5ecd4fa7400",
    "cause": "4003: Client error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed\nWASM backtrace:\nerror while executing at wasm backtrace:\n    0: 0x63a3 - <unknown>!rust_begin_unwind\n    1: 0x2eb7 - <unknown>!core::panicking::panic_fmt::hbb5a6b42001bdfec\n    2: 0x53ea58 - <unknown>!TransactionPaymentApi_query_info",
    "stack": "RpcError: 4003: Client error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed\nWASM backtrace:\nerror while executing at wasm backtrace:\n    0: 0x63a3 - <unknown>!rust_begin_unwind\n    1: 0x2eb7 - <unknown>!core::panicking::panic_fmt::hbb5a6b42001bdfec\n    2: 0x53ea58 - <unknown>!TransactionPaymentApi_query_info\n    at checkError (/usr/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/rpc-provider/cjs/coder/index.js:23:15)\n    at RpcCoder.decodeResponse (/usr/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/rpc-provider/cjs/coder/index.js:39:9)\n    at WsProvider.__internal__onSocketMessageResult (/usr/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:413:51)\n    at WebSocket.__internal__onSocketMessage (/usr/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:402:20)\n    at callListener (/usr/lib/node_modules/@substrate/api-sidecar/node_modules/ws/lib/event-target.js:290:14)\n    at WebSocket.onMessage (/usr/lib/node_modules/@substrate/api-sidecar/node_modules/ws/lib/event-target.js:209:9)\n    at WebSocket.emit (node:events:519:28)\n    at Receiver.receiverOnMessage (/usr/lib/node_modules/@substrate/api-sidecar/node_modules/ws/lib/websocket.js:1211:20)\n    at Receiver.emit (node:events:519:28)\n    at Receiver.dataMessage (/usr/lib/node_modules/@substrate/api-sidecar/node_modules/ws/lib/receiver.js:594:14)",
    "at": {
        "hash": "0xcc6bdac9fa7e9856334d1a7e8485b773a16dca6949eb73a9cef15c71ef536bb4"
    }
}

**Comment by TarikGul** [comment]
Can you provide the chain you are connected to?

**Comment by Seel555** [comment]
Thank you for your reply, we already found that runtime changed destination field, this issue can be closed

**Comment by TarikGul** [comment]
Aweomse, thanks! Closing
