### ISSUE TITLE
Tao Blockchain info":{"error":"Fee calculation not supported for this network"},

### ISSUE THREAD

**Issue by malingzhao** [paritytech/substrate-api-sidecar#1463]
tao blockchain fail to calculate fee 
curl 'http://localhost:8002/blocks/3017472/extrinsics/16?eventDocs=false&extrinsicDocs=false'
{"at":{"height":"3017472","hash":"0x4265f201d92bbffc36954941b028aef494626c1b30cb9b64e2fb8145c5426e6a"},"extrinsics":{"method":{"pallet":"balances","method":"transferKeepAlive"},"signature":{"signature":"0x15ab1d0f743d0b10f87d3c43abfea2ff09044120af045624a8a50f4d9a3680ec0ac39ed345380a4681834c408b9f199e4e61fec29e23063309d8cf98b8989e04","signer":{"id":"5ELZ1CmbFTZ144TkdJFJgyVKhdxUZy6SBjz7Ej33QtL4uYaS"}},"nonce":"0","args":{"dest":{"id":"5CMrLQwbgw5CwEqwroiahPBqHF2iwqUjHaWvi9qA278ACuNZ"},"value":"2025000000"},"tip":"0","hash":"0x836a6f90a950d6a9a1f29ffcc955e1c6f7815de42f31832115cb6d1056da8f3a","info":{"error":"Fee calculation not supported for this network"},"era":{"mortalEra":["512","253"]},"events":[{"method":{"pallet":"balances","method":"Withdraw"},"data":["5ELZ1CmbFTZ144TkdJFJgyVKhdxUZy6SBjz7Ej33QtL4uYaS","124559"]},{"method":{"pallet":"system","method":"NewAccount"},"data":["5CMrLQwbgw5CwEqwroiahPBqHF2iwqUjHaWvi9qA278ACuNZ"]},{"method":{"pallet":"balances","method":"Endowed"},"data":["5CMrLQwbgw5CwEqwroiahPBqHF2iwqUjHaWvi9qA278ACuNZ","2025000000"]},{"method":{"pallet":"balances","method":"Transfer"},"data":["5ELZ1CmbFTZ144TkdJFJgyVKhdxUZy6SBjz7Ej33QtL4uYaS","5CMrLQwbgw5CwEqwroiahPBqHF2iwqUjHaWvi9qA278ACuNZ","2025000000"]},{"method":{"pallet":"transactionPayment","method":"TransactionFeePaid"},"data":["5ELZ1CmbFTZ144TkdJFJgyVKhdxUZy6SBjz7Ej33QtL4uYaS","124559","0"]},{"method":{"pallet":"system","method":"ExtrinsicSuccess"},"data":[{"weight":{"refTime":"295649000","proofSize":"3593"},"class":"Normal","paysFee":"Yes"}]}],"success":true,"paysFee":true}}root@testWallet:/data/tao#

**Comment by TarikGul** [comment]
This is due to the `Tao` blockchain not having a chains config in sidecar - therefore it defaults to a `minCalcFeeRuntime: null`. This is where the [`chains-config`](https://github.com/paritytech/substrate-api-sidecar/tree/master/src/chains-config) is located.

This is where the error is [happening](https://github.com/paritytech/substrate-api-sidecar/blob/master/src/services/blocks/BlocksService.ts#L256-L261).

**Comment by malingzhao** [comment]
I has resolve it , you can make it be resolved
