### ISSUE TITLE
avail chain  this error

### ISSUE THREAD

**Issue by malingzhao** [paritytech/substrate-api-sidecar#1464]
{"code":500,"message":"createType(SignedBlock):: Struct: failed on block: {\"header\":\"Header\",\"extrinsics\":\"Vec<Extrinsic>\"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: findMetaCall: Unable to find Call with index [144, 29]/[144,29]","stack":"Error: createType(SignedBlock):: Struct: failed on block: {\"header\":\"Header\",\"extrinsics\":\"Vec<Extrinsic>\"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: findMetaCall: Unable to find Call with index [144, 29]/[144,29]\n    at createTypeUnsafe (/usr/src/app/node_modules/@polkadot/types-create/cjs/create/type.js:54:22)\n    at TypeRegistry.createTypeUnsafe (/usr/src/app/node_modules/@polkadot/types/cjs/create/registry.js:230:52)\n    at RpcCore._formatOutput (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:331:25)\n    at RpcCore._formatResult (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:169:20)\n    at callWithRegistry (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:190:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","level":"error"}root@testWallet:/data/avail#

**Comment by TarikGul** [comment]
What chain are you querying? What is a reproducible query I can make to get this error?

Please spend a little bit of time submitting a well written issue - so that we don't have to waste our time here.

**Comment by malingzhao** [comment]
avail chain

**Comment by malingzhao** [comment]
https://avail.subscan.io/block

**Comment by malingzhao** [comment]
I have resolve it by use  availj/sidecar-api:zenitsu

**Comment by malingzhao** [comment]
you can close as resolved
