### ISSUE TITLE
Wrong env variable in README -  'SAS_SUBSTRATE_NODE_WS_URL' 

### ISSUE THREAD

**Issue by kobrien** [paritytech/substrate-api-sidecar#147]
"SAS_SUBSTRATE_NODE_WS_URL" environment variable does not override config when starting up,  as the app defaults to 'ws://127.0.0.1:9944', changing it to "SAS_SUBSTRATE_WS_URL" seems to do the trick. *Running via docker, passing in as an env variable

**Comment by emostov** [comment]
Thank @kobrien you for pointing out the typo! Should be fixed now.
