### ISSUE TITLE
Prometheus related implementation for envvar/flag not exposed in versioned tags' codebase (deliberately?!)

### ISSUE THREAD

**Issue by jun0tpyrc** [paritytech/substrate-api-sidecar#1493]
**Description**
Ref
https://github.com/paritytech/substrate-api-sidecar/blob/master/src/main.ts#L70
https://github.com/paritytech/substrate-api-sidecar/blob/v19.1.0/src/main.ts#L70

https://github.com/paritytech/substrate-api-sidecar?tab=readme-ov-file#metrics-server
won't work

**Steps to Reproduce**
pull image https://hub.docker.com/r/parity/substrate-api-sidecar and append those flags , won't serve prometheus

**Expected vs. Actual Behavior**

should expose ?

**Comment by jun0tpyrc** [comment]
also it needs explicitly override entrypoint to add `--prometheus` to make things work at 9100
e.g.
```
  substrate-api:
    image: parity/substrate-api-sidecar:v19.1.0
    entrypoint: ["node", "build/src/main.js", "--prometheus"] # NOTE: hacky until gh issue addressed <= only can use 9100 for temp due to hardcode port
```

**Comment by Imod7** [comment]
@filvecchiato

**Comment by Imod7** [comment]
Closing this issue since the above solution is provided. Feel free to reopen in case it does not work for you.
