### ISSUE TITLE
DispatchError is not returned in `dry-run` endpoint

### ISSUE THREAD

**Issue by Imod7** [paritytech/substrate-api-sidecar#1532]
**Description**
While testing the case of this https://github.com/paritytech/substrate-api-sidecar/issues/1530, I realised that when a tx is correctly submitted but the result is a [DispatchError](https://docs.rs/sp-runtime/39.0.1/sp_runtime/enum.DispatchError.html) then the latter is not returned to the user. 
Instead we return the `Unable to dry-run transaction` error message [here](https://github.com/paritytech/substrate-api-sidecar/blob/991821d6476871d40b520a7e6e81c26d53c47afc/src/services/transaction/TransactionDryRunService.ts#L72) which is not correct since we were able to execute the dry-run

**Steps to Reproduce**
We can reproduce this by using the example mentioned in this [comment](https://github.com/paritytech/substrate-api-sidecar/issues/1530#issuecomment-2450458437). We will see that pjs apps correctly returns the corresponding dispatch error but Sidecar returns `Unable to dry-run transaction`. 

**Expected vs. Actual Behavior**
Expected : Sidecar should return the corresponding [DispatchError](https://docs.rs/sp-runtime/39.0.1/sp_runtime/enum.DispatchError.html)
Actual : Sidecar returns `Unable to dry-run transaction`

**Cause**
The issue is in this [part](https://github.com/paritytech/substrate-api-sidecar/blob/master/src/services/transaction/TransactionDryRunService.ts#L58L61) of the code where we check `response.isOk`. However, there is a second check/level of `isOk` which is `response.asOk.executionResult.isOk` and we are missing it.

**Suggested Solution**
Change the `resultType` and `result` so that it returns DispatchOutcome or DispatchError depending on the  `response.asOk.executionResult.isOk` check.

**Additional Note**
I haven't tested this case in [asset-transfer-api](https://github.com/paritytech/asset-transfer-api) but just noting here that it should be also checked to see if `asset-transfer-api` returns the DispatchError correctly.

**Comment by IkerAlus** [comment]
Re: the additional note, it shouldn't be an issue on Asset Transfer APi since it simply returns [the result of the dry run runtime API](https://github.com/paritytech/asset-transfer-api/blob/db398842d50eb88d3f2bd2344916f130cb66d5a7/src/AssetTransferApi.ts#L503).
