### ISSUE TITLE
/block     /block/NUMBER    occur  500 error code

### ISSUE THREAD

**Issue by bomax6915** [paritytech/substrate-api-sidecar#178]
{
  "code": 500,
  "message": "Cannot read property 'extrinsicBaseWeight' of undefined",
  "stack": "TypeError: Cannot read property 'extrinsicBaseWeight' of undefined\n    at ApiHandler.fetchBlock (/home/bomax/substrate-api-sidecar-test/substrate-api-sidecar/build/src/ApiHandler.js:136:55)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async BlocksController.getLatestBlock (/home/bomax/substrate-api-sidecar-test/substrate-api-sidecar/build/src/controllers/BlocksController.js:62:49)\n    at async /home/bomax/substrate-api-sidecar-test/substrate-api-sidecar/build/src/controllers/AbstractController.js:24:17"
}

**Comment by emostov** [comment]
Hi, thanks for posting an issue!

I would first try restarting Sidecar. If that does not work, it would be great if you could give more context. Some info that might help would be:

- [ ] What chain is Sidecar connected to?
- [ ] If you are running your own chain does it have any custom types?
- [ ] Does it always fail or is it just certain circumstances that it fails?

**Comment by psiofxt** [comment]
If this is still an issue for you @bomax6915 see #275
