### ISSUE TITLE
How to call rpc correctly?

### ISSUE THREAD

**Issue by zenghq3** [paritytech/substrate-api-sidecar#189]
hello,
  I currently use tag 0.12.0 docker,logs:
> docker run  -e SAS_SUBSTRATE_WS_URL=wss://rpc.polkadot.io -it -p 8080:8080 178f7196d05d

> SAS:
>   📦 EXPRESS:
>      ✅ LOG_MODE: "errors"
>      ✅ BIND_HOST: "127.0.0.1"
>      ✅ PORT: 8080
>   📦 SUBSTRATE:
>      ✅ WS_URL: "wss://rpc.polkadot.io"
> Connected to chain Polkadot on the parity-polkadot client at wss://rpc.polkadot.io
> Listening on http://127.0.0.1:8080/

Port monitoring is fine, but nothing is returned
>netstat -na|grep 8080
>tcp6       0      0 :::8080                 :::*                    LISTEN   

 then, i call 
>curl http://127.0.0.1:8080/block
>curl: (56) Recv failure: Connection reset by peer

**Comment by joepetrowski** [comment]
We're working on a fix for this, but to run in docker you'll need to set your `BIND_HOST` to `0.0.0.0` in `specs.yml`.

**Comment by emostov** [comment]
I just  put up PR #191 which fixes some of the issues.

Locally you can make the following changes as well to get up and running right now with docker:

**In the `Dockerfile`:**
Replace
```
ENV SAS_MAIN_PORT=3000
```
with
```
ENV SAS_EXPRESS_PORT=80
ENV SAS_EXPRESS_BIND_HOST=0.0.0.0
```

And also replace
```
EXPOSE ${SAS_MAIN_PORT}
```
with
```
EXPOSE ${SAS_EXPRESS_PORT}
```

**Then at the command line run:**
```
export VERSION=`cat package.json | jq -r .version`
docker run --rm -it -p 127.0.0.1:8080:80 substrate-api-sidecar:$VERSION
```
