### ISSUE TITLE
Investigate Crashes That Resolve on Restart

### ISSUE THREAD

**Issue by emostov** [paritytech/substrate-api-sidecar#193]
Several incidents have been reported that result in Sidecar to fail but resolve on restart. Up until this point those issues have not been formally documented so it is unclear if they are linked.

We may want to do some memory profiling to get a better idea if memory (mis)management is the source of this problem.

Ideally, when future issues with Sidecar come up that are resolved on restart, a detailed report of the incident can be added as a linked issue or directly in this thread.

**Comment by joepetrowski** [comment]
Log from "all" mode. Was syncing Kusama from block 2018661. Made it up to 2064961 before losing it. I didn't even need to restart it, I just stopped making requests for a few minutes and then tried one of the blocks that gave a 500 and it worked fine.
https://gist.github.com/joepetrowski/c514b411b5e28b42377929c167cc22f3

**Comment by joepetrowski** [comment]
Additional anecdotes from users:
- Only happens on Kusama/Westend. Never an issue with Polkadot.
- Resolves on restarting the node.

**Comment by jingniao** [comment]
is any process for this issue?

**Comment by emostov** [comment]
Likely fixed by #291
