### ISSUE TITLE
yarn dev error

### ISSUE THREAD

**Issue by lanyou315** [paritytech/substrate-api-sidecar#199]
Why does running YARN Dev report an error? The error message is as follows:

root@lany:/usr/local/rust/substrate-api-sidecar# yarn dev
yarn run v1.22.4
$ tsc-watch --onSuccess "yarn run main"
/bin/sh: 1: tsc-watch: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I have installed Nodejs Rustup Yarn

**Comment by lanyou315** [comment]
This has been resolved with npm install tsc-watch --save-dev

**Comment by emostov** [comment]
After cloning the repo and ensuring your machine has the proper rust dependencies installed, you should be able to install all the dependencies just by running `yarn` - after which you should be able to run `yarn dev`.
