### ISSUE TITLE
Endpoint to submit pre-signed transactions

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/substrate-api-sidecar#2]
The endpoint should accept pre-signed transactions and inject them into the transaction queue.

If the node returns an error on transaction broadcast, there must be clear documentation describing if the transaction could ever land on-chain. For example, the node should return a successful status if a transaction that sends funds from an account with insufficient balance could be persisted in the node’s transaction queue and land on chain at some point in the future when the account has sufficient balance. When in doubt, return a successful status.

**Comment by maciejhirsz** [comment]
Resolved by #21.
