### ISSUE TITLE
Unknown types found, no types for AddressStatus..., how to solve？

### ISSUE THREAD

**Issue by lanyou315** [paritytech/substrate-api-sidecar#201]
1.The contents of the custom type.JSON file are as follows:
{
  "Moment": "u64",

    "TokenTotalPower": {
    "btc_amount_power": "u64",
    "btc_count_power": "u64",
    "eth_amount_power": "u64",
    "eth_count_power": "u64",
    "usdt_amount_power": "u64",
    "usdt_count_power": "u64",
    "eos_amount_power": "u64",
    "eos_count_power": "u64"
  },

  "AssetTime": {
  "_enum": {
  "Days": "u32",
  "Minutes": "u32",
  "Hours": "u32"
  }
  },

  "AssetChangeableParams": {
  "_enum": {
  "MintPledge": "Balance",
  "BurnPledge": "Balance",
  "MintMinAmount": "Balance",
  "BurnMinAmount": "Balance",
  "MintExistsHowLong": "AssetTime",
  "MintPeriod": "AssetTime",
  "BurnExistsHowLong": "AssetTime",
  "MaxLenOfMint": "u32",
  "MaxLenOfBurn": "u32"
  }
  },

  "ChangeableParam": {
    "_enum": {

      "Alpha": "u32",
      "AmountPowerPortion": "u32",

      "MPbtc": "u32",
      "MPeth": "u32",
      "MPeos": "u32",
      "MPusdt": "u32",
      "MPecap": "u32",

      "FoundationShareRatio": "u32",
      "MinerSharePortion": "u32",
      "FatherSharePortion": "u32",
      "SuperSharePortion": "u32",

      "LCeth": "u64",
      "LAeth": "u64",

      "LCbtc": "u64",
      "LAbtc": "u64",
      "LCeos": "u64",
      "LAeos": "u64",
      "LCusdt": "u64",
      "LAusdt": "u64",
      "LCecap": "u64",
      "LAecap": "u64",

      "MLAbtc": "u64",
      "MLAusdt": "u64",
      "MLAeos": "u64",
      "MLAeth": "u64",
      "MLAecap": "u64",

      "ClientSharePortion": "u64",
      "DeclineExp": "u64"
    }
  },

  "MinerInfo": {
    "hardware_id": "Vec<u8>",
    "father_address": "Option<AccountId>",
    "grandpa_address": "Option<AccountId>",
    "register_time": "Moment",
    "machine_state": "Vec<u8>",
    "machine_owner": "AccountId"
  },

  "BurnInfo": {
    "start_block": "BlockNumber",
    "burn_man": "AccountId",
    "asset_id": "AssetId",
    "amount": "Balance",
    "foundation_tag_man": "Option<AccountId>"
  },

  "MintVote": {
    "start_block": "BlockNumber",
    "pass_block": "Option<BlockNumber>",
    "mint_block": "Option<BlockNumber>",
    "mint_man": "AccountId",
    "asset_id": "AssetId",
    "amount": "Balance",
    "approve_list": "Vec<AccountId>",
    "reject_list": "Vec<AccountId>",
    "technical_reject": "Option<AccountId>"
  },

  "AssetVote": {
    "_enum": [
      "Approve",
      "Reject"
    ]
  },

  "conviction": {
    "_enum": [
      "None",
      "Locked1x",
      "Locked2x",
      "Locked3x",
      "Locked4x",
      "Locked5x",
      "Locked6x"
    ]
  },

  "MineIndex": "u64",

  "BlockNumberOf": "u32",

  "MineTag": {
    "_enum": [
      "CLIENT",
      "WALLET"
    ]
  },

  "AddressStatus": {
    "_enum": [
      "active",
      "inActive"
    ]
  },

  "MinerStatus": {
    "_enum": [
      "Success",
      "Invalid",
      "Slashed"
    ]
  },

    "Count": "u64",

  "OwnerMineRecordItem": {
    "mine_tag": "MineTag",
    "mine_count": "u16",
    "timestamp": "Moment",
    "blocknum": "BlockNumber",
    "miner_address": "AccountId",
    "from_address": "Vec<u8>",
    "to_address": "Vec<u8>",
    "symbol": "Vec<u8>",
    "blockchain": "Vec<u8>",
    "tx": "Vec<u8>",
    "usdt_amount": "u64",
    "sym_amount": "Vec<u8>",
    "pcount_workforce": "u64",
    "decimal":"u32",
    "pamount_workforce": "u64",
    "reward": "Balance",
    "grandpa_reward": "Balance",
    "father_reward": "Balance"
  },

  "USD": "u64",

  "OwnerMineWorkForce": {
    "mine_cnt": "u64",
    "usdt_nums": "u64",
    "amount_work_force": "u64",
    "count_work_force": "u64",
    "settle_blocknumber": "u32"
  },

  "PriceInfo": {
    "dollars": "u64",
    "account": "AccountId",
    "url": "Vec<u8>"
  },

  "PriceFailed": {
    "account": "AccountId",
    "sym": "Vec<u8>",
    "errinfo": "Vec<u8>"
  },

  "PriceFailedOf": "PriceFailed",

  "VoteInfo": {
    "start_vote_block": "BlockNumber",
    "symbol": "Vec<u8>",
    "tx": "Vec<u8>",
    "reporter": "AccountId",
    "report_reason": "Vec<u8>",
    "illegal_man": "AccountId",
    "transaction_amount": "Vec<u8>",
    "usdt_amount": "Balance",
    "decimals": "u32",
    "approve_mans": "Vec<AccountId>",
    "reject_mans": "Vec<AccountId>"
  },

  "PowerInfoItem": {
    "total_power": "u64",
    "total_count": "u64",
    "count_power": "u64",
    "total_amount": "u64",
    "amount_power": "u64",
    "block_number": "BlockNumber"
  },

  "TokenPowerInfoItem": {
    "btc_total_power": "u64",
    "btc_total_count": "u64",
    "btc_count_power": "u64",
    "btc_total_amount": "u64",
    "btc_amount_power": "u64",
    "eth_total_power": "u64",
    "eth_total_count": "u64",
    "eth_count_power": "u64",
    "eth_total_amount": "u64",
    "eth_amount_power": "u64",
    "eos_total_power": "u64",
    "eos_total_count": "u64",
    "eos_count_power": "u64",
    "eos_total_amount": "u64",
    "eos_amount_power": "u64",
    "usdt_total_power": "u64",
    "usdt_total_count": "u64",
    "usdt_count_power": "u64",
    "usdt_total_amount": "u64",
    "usdt_amount_power": "u64",
    "block_number": "u64"
  },

  "MinerPowerInfoItem": {
    "miner_id": "AccountId",
    "total_power": "u64",
    "total_count": "u64",
    "count_power": "u64",
    "total_amount": "u64",
    "amount_power": "u64",
    "btc_power": "u64",
    "btc_count": "u64",
    "btc_count_power": "u64",
    "btc_amount": "u64",
    "btc_amount_power": "u64",
    "eth_power": "u64",
    "eth_count": "u64",
    "eth_count_power": "u64",
    "eth_amount": "u64",
    "eth_amount_power": "u64",
    "eos_power": "u64",
    "eos_count": "u64",
    "eos_count_power": "u64",
    "eos_amount": "u64",
    "eos_amount_power": "u64",
    "usdt_power": "u64",
    "usdt_count": "u64",
    "usdt_count_power": "u64",
    "usdt_amount": "u64",
    "usdt_amount_power": "u64",
    "block_number": "BlockNumber"
  },

  "VoteRewardPeriodEnum": {
  "_enum": {
    "Days": "u32",
    "Minutes": "u32",
    "Hours": "u32"
  }
  },

  "PermilllChangeIntoU64": "u64",

  "FetchFailedOf": {
    "timestamp": "Moment",
     "tx": "Vec<u8>",
    "err": "Vec<u8>"
  }
}

2.After running yarn Dev，The error message is as follows：
yarn run v1.22.4
$ yarn run build && yarn run main
$ tsc
$ node ./build/src/main.js
SAS:
  📦 EXPRESS:
     ✅ LOG_MODE: "all"
     ✅ BIND_HOST: "47.108.xxx.xxx"
     ✅ PORT: 8080
  📦 SUBSTRATE:
     ✅ WS_URL: "ws://47.108.xxx.xxx:9944"
Unknown types found, no types for AddressStatus, AssetChangeableParams, AssetVote, BlockNumberOf, BurnInfo, ChangeableParam, Count, FetchFailedOf, MineTag, MinerInfo, MinerPowerInfoItem, MintVote, OwnerMineRecordItem, OwnerMineWorkForce, PowerInfoItem, TokenPowerInfoItem, USD, VoteInfo, VoteRewardPeriodEnum
Unable to resolve type MineTag, it will fail on construction
2020-07-31 15:07:36        API/INIT: Error: FATAL: Unable to initialize the API: createType((Bytes,MineTag)):: Tuple: failed on 1:: Cannot construct unknown type MineTag
    at EventEmitter.value (/usr/local/rust/substrate-api-sidecar/node_modules/@polkadot/api/base/Init.js:77:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at processImmediate (internal/timers.js:429:9)
Error: FATAL: Unable to initialize the API: createType((Bytes,MineTag)):: Tuple: failed on 1:: Cannot construct unknown type MineTag
    at EventEmitter.value (/usr/local/rust/substrate-api-sidecar/node_modules/@polkadot/api/base/Init.js:77:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at processImmediate (internal/timers.js:429:9)

**Comment by emostov** [comment]
Have you reviewed this FAQ https://polkadot.js.org/api/start/FAQ.html#i-am-getting-a-unknown-types-found-no-types-for-error ?

Have you made sure to follow all the guidance on this page about extending types https://polkadot.js.org/api/start/types.extend.html ?

**Comment by lanyou315** [comment]
Thank you very much. I'm looking up the FAQ .
