### ISSUE TITLE
Set `tip` and `nonce` to null for unsigned transactions and inherents in `/block` response

### ISSUE THREAD

**Issue by emostov** [paritytech/substrate-api-sidecar#215]
Currently, inherents and unsigned transactions have a `tip` and `nonce` field despite the information not being relevant to there validation or execution. These fields should thus be set to null.

Additionally, it is worth investigating if `paysFee` should always be false for inherents. Currently inherents always have pays fee as true because the `system.ExtrinsicSuccess` seems to default to having it as a true value despite inherents not having any users and not paying any fees.

**Comment by zhenghq** [comment]
inherents and unsigned transactions seem to be indistinguishable now.
