### ISSUE TITLE
Unknown types found, no types for Difficulty, DifficultyAndTimestamp, Era

### ISSUE THREAD

**Issue by xianggy** [paritytech/substrate-api-sidecar#238]
try to connect to kulupu and the response shows:

$ node ./build/src/main.js
SAS:
  📦 EXPRESS:
     ✅ LOG_MODE: "errors"
     ✅ BIND_HOST: "127.0.0.1"
     ✅ PORT: 8080
  📦 SUBSTRATE:
     ✅ WS_URL: "ws://127.0.0.1:8101"
Unknown types found, no types for Difficulty, DifficultyAndTimestamp, Era
Connected to chain Kulupu on the kulupu client at ws://127.0.0.1:8101
Listening on http://127.0.0.1:8080/

the api `http://127.0.0.1:8080/block` gets 0, is that correct?

thank you.

**Comment by emostov** [comment]
You will need to enter the definition for those types. Here is how to define the types: https://polkadot.js.org/api/start/types.extend.html. 

You will need to put the type definitions in this config file: https://github.com/paritytech/substrate-api-sidecar/blob/master/config/types.json. I think these would work: https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/api/spec/kulupu.ts

`http://127.0.0.1:8080/block` fetches the latest finalized block. So this would only be block 0 if your chain has only finalized block 0. Block endpoint docs here: https://github.com/paritytech/substrate-api-sidecar/blob/master/src/controllers/blocks/BlocksController.ts#L13

If you have more issues using Kulupu after correctly entering in the custom types, let us know.
