### ISSUE TITLE
Run yarn start failed

### ISSUE THREAD

**Issue by JaniceLee629** [paritytech/substrate-api-sidecar#24]
When I update the latest version of the program and run it on a mac, I get this error

yarn run v1.22.0
$ tsc && node ./build/main.js
Running on http://127.0.0.1:18080/
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 127.0.0.1:18080
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at doListen (net.js:1496:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1336:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 18080
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I checked, 18080 port is not occupied by other programs

**Comment by joepetrowski** [comment]
There have been some updates since this was posted. I just ran on a macbook pro without problem. Is it a specific block or endpoint that gave a problem?

**Comment by joepetrowski** [comment]
Closing as this is out of date
