### ISSUE TITLE
Transaction Construction Endpoint

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/substrate-api-sidecar#25]
Make an endpoint that returns everything needed to make transactions in txwrapper. It should take an optional block number (return the finalized head if not provided) and return:

- metadata
- runtime spec version
- checkpoint block number (finalized head or param)
- checkpoint block hash

```
txConstruction(block: number) -> (
    metadata: string,
    specVersion: number,
    blockNumber: number,
    blockHash: string
)
```

**Comment by maciejhirsz** [comment]
Fixed in #33.
