### ISSUE TITLE
Timeout on some blocks

### ISSUE THREAD

**Issue by dvneverov** [paritytech/substrate-api-sidecar#255]
Hi! 
Found out that sidecar api throws timeout on some block, like this: https://polkadot-api.w3f.community/block/1383756

**Comment by emostov** [comment]
I am not able to reproduce. What error code are you getting?

**Comment by dvneverov** [comment]
Looks like it was the problem on the side of https://polkadot-api.w3f.community/ 
Their cloudflare was sending 524 timeout on this block, but now it works fine.
