### ISSUE TITLE
/block returns 500 on Kusama

### ISSUE THREAD

**Issue by psiofxt** [paritytech/substrate-api-sidecar#275]
**Description**
KUSAMA

Using Polkadot 0.8.23 and api-sidecar 0.16.0 any block except block 0 throws a
```
{ ... "message": "Cannot read property 'extrinsicBaseWeight' of undefined" ... }
```

**Steps to Reproduce**

While a Kusama node is syncing attempt to use the `/block` endpoint

Same error as issue #178

**Comment by psiofxt** [comment]
Furthermore, it is failing at this line https://github.com/paritytech/substrate-api-sidecar/blob/227cc69f97ba0106fd069f6d644960987fdc0c84/src/services/v0/v0blocks/BlocksService.ts#L308

claiming `api.consts.system` does not exist. Is this due to the fact the node is still syncing?

**Comment by emostov** [comment]
Thank you for pin pointing the line of failure. I would wait until you node is done syncing and then connect Sidecar and try. Let us know if the issue persists.

**Comment by psiofxt** [comment]
The runtimes needed to catch up it seems. This is resolved thanks @emostov
