### ISSUE TITLE
Investigate middleware validation for `/pallets` URIs

### ISSUE THREAD

**Issue by emostov** [paritytech/substrate-api-sidecar#281]
Look into if having some sort of validation middleware for `palletId` and/or `storageItemId`, `errorId`, `eventId`, `callId` makes sense. This would probably look similar to validation middleware for `address`

**Comment by TarikGul** [comment]
@emostov, being that the middleware would have to parse some metadata in order to validate the Id's I dont think this is as useful anymore, and any check or error could be thrown via the service. 

Closing.
