### ISSUE TITLE
get block info error

### ISSUE THREAD

**Issue by qixiuyuan** [paritytech/substrate-api-sidecar#299]
**Description**

getblocks error 

**Steps to Reproduce**

http://****:8080/blocks/1603921

**Expected vs. Actual Behavior**

{
    "code": 500,
    "message": "createType(SignedBlock):: Struct: failed on 'block':: Struct: failed on 'extrinsics':: createType(ExtrinsicV4):: createType(Call):: Struct: failed on 'args':: Unable to create Enum via index 3, in Staked, Stash, Controller",
    "stack": "Error: createType(SignedBlock):: Struct: failed on 'block':: Struct: failed on 'extrinsics':: createType(ExtrinsicV4):: createType(Call):: Struct: failed on 'args':: Unable to create Enum via index 3, in Staked, Stash, Controller\n    at createTypeUnsafe (/mnt/rust/substrate-api-sidecar-master/node_modules/@polkadot/types/create/createType.js:69:11)\n    at Rpc._formatOutput (/mnt/rust/substrate-api-sidecar-master/node_modules/@polkadot/rpc-core/index.js:377:40)\n    at callWithRegistry (/mnt/rust/substrate-api-sidecar-master/node_modules/@polkadot/rpc-core/index.js:222:62)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
}

**Comment by emostov** [comment]
What version of Sidecar are you using? This error should have been fixed in v0.18.1.

**Comment by qixiuyuan** [comment]
Hello! Thank you very much for your reply.
This problem, I restart the service, and it will be OK







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "paritytech/substrate-api-sidecar"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月21日(星期一) 晚上9:27
收件人:&nbsp;"paritytech/substrate-api-sidecar"<substrate-api-sidecar@noreply.github.com&gt;;
抄送:&nbsp;"于修远"<972863244@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [paritytech/substrate-api-sidecar] get block info error (#299)





 
What version of Sidecar are you using? This error should have been fixed in v0.18.1.
