### ISSUE TITLE
Inquire about individual transaction details

### ISSUE THREAD

**Issue by satonz** [paritytech/substrate-api-sidecar#306]
Based on the transaction hash, what should I do to query the transaction details

**Comment by emostov** [comment]
tl;dr you can not use the transaction hash; to you uniquely identify a transaction you need the block hash the transaction was included in and the index of the transaction within the block. You can read more here: https://wiki.polkadot.network/docs/en/build-protocol-info#unique-identifiers-for-extrinsics
