### ISSUE TITLE
Unable to submit transaction

### ISSUE THREAD

**Issue by satonz** [paritytech/substrate-api-sidecar#312]
{"code":500,"error":"Failed to submit transaction.","transaction":"0x390284de11bef8cb54a7787af6ae41a68e1cbffe8a5849c40b5a4585e6089215a8a24801d6198388588126468fdbc2facb045cdc9f36a5a41fd4a9cfd4242c8d89ae274e96111654d2d15883483ae3854d9b919786b23164bd669c3239e05d2f41ac438e009101000500bce3f7344d9037f8e4c6484d9198c1411ff4b418a7cc9edc3c4298d9c254256e0700c817a804","cause":"1010: Invalid Transaction: Custom error: 2","stack":"Error: 1010: Invalid Transaction: Custom error: 2\n    at RpcCoder._checkError (/substrate-api-sidecar/node_modules/@polkadot/rpc-provider/coder/index.js:84:13)\n    at RpcCoder.decodeResponse (/substrate-api-sidecar/node_modules/@polkadot/rpc-provider/coder/index.js:47:10)\n    at WsProvider.value (/substrate-api-sidecar/node_modules/@polkadot/rpc-provider/ws/Provider.js:215:90)\n    at W3CWebSocket.value [as onmessage] (/substrate-api-sidecar/node_modules/@polkadot/rpc-provider/ws/Provider.js:195:153)\n    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/substrate-api-sidecar/node_modules/yaeti/lib/EventTarget.js:107:17)\n    at W3CWebSocket.onMessage (/substrate-api-sidecar/node_modules/websocket/lib/W3CWebSocket.js:234:14)\n    at WebSocketConnection.<anonymous> (/substrate-api-sidecar/node_modules/websocket/lib/W3CWebSocket.js:205:19)\n    at WebSocketConnection.emit (events.js:315:20)\n    at WebSocketConnection.processFrame (/substrate-api-sidecar/node_modules/websocket/lib/WebSocketConnection.js:554:26)\n    at /substrate-api-sidecar/node_modules/websocket/lib/WebSocketConnection.js:323:40"}

**Comment by satonz** [comment]
![image](https://user-images.githubusercontent.com/38401802/95553791-bcb40b00-0a41-11eb-97f4-1c6337d2da70.png)
Show that the transaction has been imported, the transaction cannot be queried on the blockchain

**Comment by satonz** [comment]
![Uploading image.png…]()

**Comment by satonz** [comment]
![image](https://user-images.githubusercontent.com/38401802/95553962-fdac1f80-0a41-11eb-8219-03ac353c0c62.png)

**Comment by emostov** [comment]
What chain and spec version are submitting the transaction to?

**Comment by emostov** [comment]
I tried to decode you transaction against polkadot and it would not work. It specifically fails on trying to decode the signature - which could be a misleading error but at least a starting point.

You should be able to decode a valid transaction like so:

```
	const api = new ApiPromise({
		provider: new WsProvider('wss://rpc.polkadot.io'),
	});

	const ext = api.createType(
		'Extrinsic',
		'0x390284de11bef8cb54a7787af6ae41a68e1cbffe8a5849c40b5a4585e6089215a8a24801d6198388588126468fdbc2facb045cdc9f36a5a41fd4a9cfd4242c8d89ae274e96111654d2d15883483ae3854d9b919786b23164bd669c3239e05d2f41ac438e009101000500bce3f7344d9037f8e4c6484d9198c1411ff4b418a7cc9edc3c4298d9c254256e0700c817a804'
	);

	console.log(ext.toHuman());
```

**Comment by satonz** [comment]
I use Golang for development, and the chain type is Polkdot, so how should I build the transaction? I would like to ask if there is any relevant demo, thank you

**Comment by emostov** [comment]
https://github.com/paritytech/txwrapper

demo: https://github.com/paritytech/txwrapper/blob/master/examples/polkadot.ts

Also, you can try out polkadot-js: https://polkadot.js.org/docs/api/examples/promise/make-transfer
