### ISSUE TITLE
Investigate strategies to maintain service through lossy websocket connection

### ISSUE THREAD

**Issue by emostov** [paritytech/substrate-api-sidecar#326]
Relates to #317 

Strategies should be investigated that intend to make sure sidecar can keep running when websocket connections disconnect

This may be a modification at the `ApiPromise` level, or could even involve sidecar restarting itself.

**Comment by dvdplm** [comment]
I think doing this is a good idea. The tricky part might be knowing (reliably) when a websocket is disconnects in such a way that a reconnect makes sense, but it can be a QoL improvement for 80% of users.
I suggest we make it a config option that is off by default and with a default value set fairly high, 30sec or so, to avoid spam. If it pans out and users are happy it can become an on-by-default value in a subsequent breaking release.

**Comment by anhcao142** [comment]
Hi, sorry to bring this up again, but why don't you consider using the HTTP/HTTPS method?

**Comment by TarikGul** [comment]
@anhcao142 Do you mind going a little more in detail. 

Under the hood the connection is being established by `@polkadot/api` which leverages websocket connection. I am not sure I understand the use case for HTTP/HTTPs here but I might be missing something.

**Comment by anhcao142** [comment]
Hi @TarikGul, the `@polkadot/rpc-provider` provides both `WsProvider` and `HttpProvider` to respectively connect to the node through WebSocket and RPC. So it's possible for `substrate-api-sidecar` to connect to the node through WebSocket and HTTP too.

**Comment by anhcao142** [comment]
To demonstrate, here is my modified version of `substrate-api-sidecar` in order to connect to the node through the RPC port

```
import { WsProvider, HttpProvider } from '@polkadot/rpc-provider';

async function main() {
	const { config } = SidecarConfig;
	const { logger } = Log;
	// Overide console.{log, error, warn, etc}
	consoleOverride(logger);
	logger.info(`Version: ${packageJSON.version}`);
	const { TYPES_BUNDLE, TYPES_SPEC, TYPES_CHAIN, TYPES } = config.SUBSTRATE;
	// Instantiate a web socket connection to the node and load types
	const api = await ApiPromise.create({
		provider: config.SUBSTRATE.URL.startsWith('http')
			? new HttpProvider(config.SUBSTRATE.URL) // <-- I connect to the node using RPC here
			: new WsProvider(config.SUBSTRATE.URL),
		/* eslint-disable @typescript-eslint/no-var-requires */
		typesBundle: TYPES_BUNDLE
			? (require(TYPES_BUNDLE) as OverrideBundleType)
... // rest of code
```

**Comment by TarikGul** [comment]
Ahhh okay that is super helpful, thanks so much for the provided example and explanation. It's getting late for me, but I will look more into it tomorrow morning and see what kind of solution we can get implemented and put it on our roadmap :)

**Comment by TarikGul** [comment]
@emostov @dvdplm Got any opinions on the HttpProvider?

**Comment by emostov** [comment]
Seems reasonable to me

**Comment by TarikGul** [comment]
This seems to not be an issue anymore, and the WebSocket on the polkadot-js connection side is stable enough to close this issue. Unless this comes up again we can close it for now. I created a seperate issue to add the http support https://github.com/paritytech/substrate-api-sidecar/issues/999
