### ISSUE TITLE
can't get block by height

### ISSUE THREAD

**Issue by jaslin-W** [paritytech/substrate-api-sidecar#341]
polkadot node version v0.8.26-1
substrate-v1.0.0

i call /blocks/{blockId} by height. But i get an error. i follow the api doc

![2](https://user-images.githubusercontent.com/65018397/98908975-266d7c00-24fc-11eb-8b21-573f1627631b.png)
![1](https://user-images.githubusercontent.com/65018397/98908982-28373f80-24fc-11eb-8b65-0f6586006166.png)

**Comment by dvdplm** [comment]
"State already discarded for BlockId::Hash": sounds like the node you're querying does not have the state for the block anymore. How are you running the node? Can you query a more recent block? Can you sync your node with `--pruning=archive` (so no old data is discarded)?

**Comment by jaslin-W** [comment]
thanks. i  will try to run the node with this option

**Comment by jaslin-W** [comment]
i resolve this problem by run node with `--pruning=archive`.
Thank you very much!
