### ISSUE TITLE
How to get finalized block though height or hash?

### ISSUE THREAD

**Issue by Swain-Xie** [paritytech/substrate-api-sidecar#358]
Is there any attributes can be used to distinguish between finalized block and unfinalized block ? 

or maybe there is a endpoint for get finalized block though height or hash ?

Really thank for you reply!

**Comment by Swain-Xie** [comment]
Or Is there a way to determine whether a block is finalized though number or height ？

**Comment by emostov** [comment]
`blocks/head` will return the most recently finalized block. `blocks/head?finalized=false` will return the highest known block on the canon chain, which may or may not be finalized. 

Any block that is the parent of a finalized block (i.e its number is lower than a finalized block) and is on the canon chain is considered finalized. For example, if block 10 has just been finalized, then blocks 1 through 9 on the canon chain are also finalized.

Docs for the `blocks/head` endpoint here:
https://github.com/paritytech/substrate-api-sidecar/blob/692193d38c0d21b6afe500d01437e53acc76c964/docs/src/openapi-v1.yaml#L267-L307

The docs also have  a [GUI here](https://paritytech.github.io/substrate-api-sidecar/dist/)
