### ISSUE TITLE
Get account balance at a block number

### ISSUE THREAD

**Issue by schadokar** [paritytech/substrate-api-sidecar#359]
**Proposed Change or Idea**

Get account balance at a particular block number.

**Additional Information**

@chevdor 
In the previous version this api was available.  
`/balance/ADDRESS/NUMBER` fetch balances for ADDRESS at the block identified by 'NUMBER`.  

Why it is not available in the latest version?

**Comment by Swader** [comment]
https://paritytech.github.io/substrate-api-sidecar/dist/


Replacement is documented in API docs, first entry.

**Comment by schadokar** [comment]
Thank you. I didn't checked by expanding it.
