### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by gavinbd** [paritytech/substrate-api-sidecar#363]
**Description**

After a period of time the API no longer responds to queries and just dumps memory allocation errors. But there is a steady creep in memory allocation over time. The dip you see is me having to restart the container manually.

<img width="1782" alt="Screenshot 2020-12-14 at 09 52 02" src="https://user-images.githubusercontent.com/63361084/102067490-12ff4a80-3df3-11eb-9982-e340746b1806.png">

2020-12-12 13:08:24 error: GET /blocks/head 500 42ms
2020-12-12 13:10:57 error: unreachable
 RuntimeError: unreachable
    at __wbindgen_malloc (wasm-function[186]:0x15478)
    at passStringToWasm0 (/app/node_modules/@substrate/calc/calc.js:25:17)
    at Function.from_params (/app/node_modules/@substrate/calc/calc.js:97:24)
    at BlocksService.createCalcFee (/app/build/src/services/blocks/BlocksService.js:249:37)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async BlocksService.fetchBlock (/app/build/src/services/blocks/BlocksService.js:55:52)
    at async BlocksController.getLatestBlock (/app/build/src/controllers/blocks/BlocksController.js:77:49)
    at async /app/build/src/controllers/AbstractController.js:138:9

**Steps to Reproduce**

This happened 12 days after updating so it seems to trigger after a period of time. The same issue also occurred on the release candidate but we held off on reporting it due to being RC.

**Expected vs. Actual Behavior**

Expect a 200, got an error instead. This then occurs on all subsequent API calls.

Restarting the container fixes the issue.

**Comment by emostov** [comment]
Thank you for the detail info-graphs.

Do you have any other processes besides Sidecar running in the container (like a polkadot node)? The node heap memory allocation limit on a 64bit machine is around 2gb (unless you have modified it with something like `--max-old-space-size`) - so I would think it would be crashing around that if running alone in a container. That graph on the bottom left looks like its consistently over 4gb, making me think something else is running in the container and possibly having the memory leak?

Do you have any other info about request load/ frequency and on what endpoints so we can try and replicate?

Not ideal, but a short term solution might be to run 2 Sidecar processes behind a reverse proxy and rotate between the two with offset restarts.

**Comment by gavinbd** [comment]
Yes we have polkadot running too. We think it might be the substrate process I just jumped to the conclusion it was sidecar as it was the one logging the error. Ill close this and re-open if I find any more information.
