### ISSUE TITLE
Staking-payouts with large depths not successful

### ISSUE THREAD

**Issue by wpank** [paritytech/substrate-api-sidecar#367]
Queries with large depths do not successfully return, such as:
(polkadot)
`/staking-payouts?depth=83&&era=197&unclaimedOnly=true`

They will return an error such as:

```
  message: 'request to http://<endpoint>/accounts/<account_address>/staking-payouts?depth=83&&era=197&unclaimedOnly=true failed, reason: socket hang up',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
  ````

This generally happens for any depth greater than 10. This used to work with pretty large depths.

**Comment by emostov** [comment]
Noting here that querys of depth 83 are consistently taking about 5 minutes against `wss://rpc.polkadot.io` using postman on my local machine. 

In google chrome, with `depth=3` and I above I consistently get the error:
```
Your connection was interrupted
A network change was detected.
ERR_NETWORK_CHANGED
```

My hypothesis is that various clients have some variant of a time out error and Sidecar it self is not necessarily failing or even hanging.

My next steps will include closely investigating the exact error messages, looking into optimzations of the endpoint and potentially redesigning the end point interface in a way that would be less susceptible to time errors.

One potential design brainstormed by @danforbes essentially involves a POST endpoint to create a resource that is the status of the query (returns an ID) and then a GET endpoint to poll the resource, returning the status of the query and possibly the result when done.
