### ISSUE TITLE
Log slow requests as warnings

### ISSUE THREAD

**Issue by emostov** [paritytech/substrate-api-sidecar#373]
In order to help Sidecar maintainers and sysadmins better trouble shoot issues with the service and its deployment it may be helpful to log slow requests at the `warn` log level (or log an additional message at the `warn` log level with every slow request).

rel: #368

**Comment by danforbes** [comment]
Could we allow Sidecar admins to configure what is considered a "slow" request? Is there existing Express middleware or something that handles this?

**Comment by TarikGul** [comment]
Our recent benchmarks of all the endpoints have shown that consumption of resources vastly vary across each service, therefore it's harder to track what is "slow" and what isn't. I would argue a better source of truth should be the benchmarks and we work on performance regressions from there. Closing.
