### ISSUE TITLE
Mention resource requirements in README

### ISSUE THREAD

**Issue by emostov** [paritytech/substrate-api-sidecar#374]
Investigate the following:

> I'm wondering, maybe is memory usage at 600 MB avg 1 GB peak expected, and my instance is just underprovisioned? If so the resource requirements should probably be mentioned in the docs to help people with capacity planning.

_Originally posted by @terorie in https://github.com/paritytech/substrate-api-sidecar/issues/368#issuecomment-748957493_

**Comment by TarikGul** [comment]
closing via https://github.com/paritytech/substrate-api-sidecar/pull/872
