### ISSUE TITLE
Get historical transaction records based on address

### ISSUE THREAD

**Issue by vae520283995** [paritytech/substrate-api-sidecar#377]

**Comment by emostov** [comment]
You will need to index the blocks in the chain (normally from genesis). Sidecar is stateless, so it can be used to retrieve the data per block height, but it cannot give you a collection of data spanning multiple heights in a single query. 

Here is an example of a community written indexer based on sidecar: https://github.com/kianenigma/substrate-api-sidecar-dump

**Comment by vae520283995** [comment]
> You will need to index the blocks in the chain (normally from genesis). Sidecar is stateless, so it can be used to retrieve the data per block height, but it cannot give you a collection of data spanning multiple heights in a single query.
> 
> Here is an example of a community written indexer based on sidecar: https://github.com/kianenigma/substrate-api-sidecar-dump

ok, thank you
