### ISSUE TITLE
Investigate adding finalized tag to block metadata 

### ISSUE THREAD

**Issue by emostov** [paritytech/substrate-api-sidecar#378]
**Proposed Change or Idea**

If a user queries a block by ID it would be convenient for them to immediately know if it is considered finalized at the time of querying. 

An alternate would be for the user to query `blocks/head` and compare that block's height to the block they are checking if it is finalized. If the height of the block they are checking finality for is higher then `blocks/head` they can assume it is not finalized

**Comment by dvdplm** [comment]
Seems like a good QoL improvement for users. I like it.

**Comment by TarikGul** [comment]
@dvdplm @emostov Would you guys like a simple key such as `isFinalized: boolean` to be returned in the output reponse?

**Comment by emostov** [comment]
@TarikGul yes, I personally like `finalized: boolean`.
