### ISSUE TITLE
Continuous package publishing

### ISSUE THREAD

**Issue by emostov** [paritytech/substrate-api-sidecar#380]
Ideally, each Monday, once polkadot-js scoped deps publish a new release we can try to automatically merge the new polkadot-js deps and then do an automated release with changelog generation, new tag, and publish to NPM.

**Comment by dvdplm** [comment]
I wonder how this would jive with 2-reviews-to-merge. What we want is some sort of override for that setting such that iff we get a clean merge and CI runs green it's ok to automerge.

**Comment by TarikGul** [comment]
From what I have looked into, we can create a `dependabot.yml` and schedule pull requests for every monday to update packages we specify. We have the ability to assign reviewers as well. The only issue is how to bypass the reviewers.

**Comment by emostov** [comment]
@TarikGul do you know how we can generate a `github_token`? If not I think @dvdplm would know who to ask.

**Comment by emostov** [comment]
Also worth noting the current release workflow with the `deploy` script is broken. We manually edited the auto generated change log awhile back and I think that broke it. Maybe we can deprecate the current changelog and start fresh with a new changelog the complies without whatever release tool we decide to use?

**Comment by TarikGul** [comment]
> @TarikGul do you know how we can generate a `github_token`? If not I think @dvdplm would know who to ask.

I believe the person with the admin rights to the repository can make a `github_token`. 

> Also worth noting the current release workflow with the `deploy` script is broken. We manually edited the auto generated change log awhile back and I think that broke it. Maybe we can deprecate the current changelog and start fresh with a new changelog the complies without whatever release tool we decide to use?

Yea i think thats worth updating as well. In the long run it will save us a lot of time, if we can make it do the right things efficiently. Im into it. Yea I don't know what the side effects would be if we deprecated the change log and started with a new one, I dont think it would be much. I will definitely check it out.

**Comment by dvdplm** [comment]
> I believe the person with the admin rights to the repository can make a `github_token`.

FWIW you are both admins here.

**Comment by TarikGul** [comment]
Part one of this issue is is merged. A pre-release dependabot that creates PR's every monday for updated polkadot dependencies. 

The next part will be to upgrade the current Changelog generation. One solution me and Zeke have talked about is deprecating the current changelog, and creating a new workflow that will automate future changelogs.

**Comment by dvdplm** [comment]
>  One solution me and Zeke have talked about is deprecating the current changelog

Indeed. No intrinsic value in the git history of `CHANGELOG` I think. :)

**Comment by TarikGul** [comment]
Closing in favor of our current workflow.
