### ISSUE TITLE
partialFee value is always 0 on local development with polkadot 1.8.27

### ISSUE THREAD

**Issue by islishude** [paritytech/substrate-api-sidecar#385]
**Description**
nodejs version: v14 LTS
polkadot version: 1.8.27
sidecar version: latest commit

**Steps to Reproduce**

make a transfer at polkadot.js.org/app,and request block info

![截屏2021-01-13 下午6 09 40](https://user-images.githubusercontent.com/24730006/104438100-923a9680-55ca-11eb-9c22-30b8720a0fab.png)

polkadot 1.8.26-1 is ok

**Expected vs. Actual Behavior**

[A clear description of what you expected to happen and what actually happened.]

**Comment by emostov** [comment]
rel: https://github.com/paritytech/substrate/pull/6629

**Comment by emostov** [comment]
`ExtrinsicBaseWeight` is no longer a constant in the system pallet and the fee calculations need to be updated.

**Comment by vae520283995** [comment]
I have the same problem

**Comment by vae520283995** [comment]
> I have the same problem

Fortunately, this is the testnet. If it is the mainnet, the consequences will be disastrous.
