### ISSUE TITLE
Can I configure custom types via environment variables?

### ISSUE THREAD

**Issue by ntduan** [paritytech/substrate-api-sidecar#387]
If I start service from the source code, I can modify the config/types file to add custom types, but if I want to start service from the command line, I don't find a way to configure custom types.

**Comment by emostov** [comment]
At the moment the only way to modify the custom types is to go into `config/types.json`, which technically you could do by going to where the NPM package is installed and modifying it there. However that obviously is not ideal and would be overridden any time you go to update the package. 

So this feature sounds like a good idea to me.

@ntduan do you think an ok would alternative would be to have an environment variable like `SAS_SUBSTRATE_TYPES="path/to/my-custom-types.json"?

**Comment by ntduan** [comment]
> At the moment the only way to modify the custom types is to go into `config/types.json`, which technically you could do by going to where the NPM package is installed and modifying it there. However that obviously is not ideal and would be overridden any time you go to update the package.
> 
> So this feature sounds like a good idea to me.
> 
> @ntduan do you think an ok would alternative would be to have an environment variable like `SAS_SUBSTRATE_TYPES="path/to/my-custom-types.json"?

I'm not quite sure what it should look like. Since the types obtained from `@polkadot/app-config` may not be up to date, I would like to be able to update the types myself. And it would be nice to be able to support typeBundle in the following form.
```
{
    minmax: [0, 499] ,
    type: {
      ...
    }
  },
  {
    minmax: [500, 599] ,
    type: {
      ...
    }
  },
 {
    minmax: [599, undefined] ,
    type: {
      ...
    }
  },
```

**Comment by emostov** [comment]
Ok, in that case I think a solution that simultaneously supports dynamically specifying `typeBundle`,  `typeSpec`, `typesChain`, and `types` would be ideal. Essentially we want to allow a api-sidecar user to have the ability to have the ability to override any of these fields:

https://github.com/paritytech/substrate-api-sidecar/blob/9d89309bb27e5a7bd47d287d9dbb76e725dd5abf/src/main.ts#L38-L46

**Comment by emostov** [comment]
On the topic of keeping `polkadot/apps-config` up to date, one of the TODOs for sidecar is to automate publishing so whenever any polkadot-js dependency updates we automatically publish a new patch release of api-sidecar (see https://github.com/paritytech/substrate-api-sidecar/issues/380)

**Comment by emostov** [comment]
@ntduan let me know wether or not #399 looks like a solution that should work for your use case.

**Comment by ntduan** [comment]
@emostov  I think it looks good
