### ISSUE TITLE
sidecar does not reconnect if substrate node restarts

### ISSUE THREAD

**Issue by jadechip** [paritytech/substrate-api-sidecar#418]
**Proposed Change or Idea**

The substrate-api-sidecar service does not attempt to reconnect if the associated substrate node goes down or restarts.
This is particularly troublesome in a Kubernetes environment where deployments often trigger pods to restart.

**Alternatives**

The substrate-api-sidecar service could periodically attempt to reconnect to the substrate node.

**Additional Information**

[Add any other details about the feature request here.]

**Comment by emostov** [comment]
Possibly relates to #326

**Comment by TarikGul** [comment]
Closing in favor of this tracking issue [#719](https://github.com/paritytech/substrate-api-sidecar/issues/719).

Polkadot-js has a few built it ws-options, and default behavior for reconnecting. One way to confirm this locally, is have sidecar connected to a public node, then turn off the wifi, and turn it back on.
