### ISSUE TITLE
Gitignore fee files and swagger dist folder

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/substrate-api-sidecar#421]
When I run `CALC_DEBUG=1 sh calc/build.sh ` it generates this files
calc/pkg/calc.js
calc/pkg/calc_bg.wasm

Also when we build the Swagger docs with `cd docs/ && yarn && yarn build`, it generates
docs/dist/app.bundle.js

Could we add these to the .gitignore file?

**Comment by emostov** [comment]
These files are intentionally checked into git.
