### ISSUE TITLE
Remove the `calc` crates dependence on `sp-arithmetic-legacy`

### ISSUE THREAD

**Issue by emostov** [paritytech/substrate-api-sidecar#430]
Currently, the `calc` crate relies on an old commit of substrate to reproduce a bug a in an old version of sp-arithmetic that affected fee calculations. Relying on old substrate commits will not work long term. Some options for tackling this issue that where proposed offline by @dvdplm include: 

* backport needed fixes to old substrate and maintain that fork forever
* copy the needed parts from old substrate and maintain only those forever, inside calc
* something else I haven't thought of

**Comment by dvdplm** [comment]
cc @athei
