### ISSUE TITLE
Add unit tests directly to `calc` crate and generated JS

### ISSUE THREAD

**Issue by emostov** [paritytech/substrate-api-sidecar#431]
Currently, the `calc` crate has no tests directly in the crate or directly on the generated JS target functions. We do though test `calc` in api-sidecar. 

Adding tests directly will not only improve our ability to build quickly without breaking things, but it will also help document the `calc` crates public API (which is important because it is published on NPM).

**Comment by TarikGul** [comment]
#802 Adds tests for `impl Multiplier` but the tests now should also extend to `CalcFee` which would be the next step. 

Might be also nice to get some tests in place for Calc Payouts

**Comment by TarikGul** [comment]
Closing this as we are phasing out of `@substrate/calc`.
