### ISSUE TITLE
Cannot read property 'extrinsicBaseWeight' of undefined

### ISSUE THREAD

**Issue by Swader** [paritytech/substrate-api-sidecar#437]
#135 seems unresolved.

Am getting this during normal operations when connecting to a Kusama archive node that's still syncing. You can try the endpoint out live here: https://sidecar.rmrk.app

**Comment by Swader** [comment]
More details:

- it's a Kusama archive node
- I'm passing through Nginx

**Comment by TarikGul** [comment]
Hey @Swader, Thanks for bringing up this issue. Going to request access to the node so I can do some direct testing / debugging. 

I cant seem to reproduce the error on Kusama itself. Is there any additional logging information that could be useful that is showing up in the terminal running sidecar? 

This is the current error I am getting via the endpoint you provided. Which in itself is already pretty informative.

```
{"code":500,"message":"Cannot read property 'extrinsicBaseWeight' of undefined","stack":"TypeError: Cannot read property 'extrinsicBaseWeight' of undefined\n    at BlocksService.createCalcFee (/usr/local/bin/node_modules/@substrate/api-sidecar/build/src/services/blocks/BlocksService.js:310:61)\n    at BlocksService.fetchBlock (/usr/local/bin/node_modules/@substrate/api-sidecar/build/src/services/blocks/BlocksService.js:85:96)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async BlocksController.getBlockById (/usr/local/bin/node_modules/@substrate/api-sidecar/build/src/controllers/blocks/BlocksController.js:125:49)\n    at async /usr/local/bin/node_modules/@substrate/api-sidecar/build/src/controllers/AbstractController.js:139:9","level":"error"}
```

Have you seen this issue on the Kusama chain as well, and if so do you have a specific block number I could test and debug against? 

The main issue being that it potentially isn't reading the `api.consts.system` before it reads into `extrinsicBaseWeight` on line [467](https://github.com/paritytech/substrate-api-sidecar/blob/master/src/services/blocks/BlocksService.ts#L467) which is causing this to throw the error (But this is also speculation).

 I'll continue to look into this, and any additional information would be great. Thanks.

**Comment by kianenigma** [comment]
Had the same issue and installing a fresh updated version of sidecar fixed it. Apparently my global version was kinda screwed and I failed to update it.

**Comment by Swader** [comment]
All good, a `yarn upgrade` of my sidecar (even though this one was freshly installed!) fixed things. I can now hit the endpoint.
