### ISSUE TITLE
/accounts/{accountId}/balance-info Error returning data

### ISSUE THREAD

**Issue by sugeladi** [paritytech/substrate-api-sidecar#441]
**Description**

The request RPC interface returned an error，The free field in response is very large。
Polkadot v0.8.28-1
substrate-api-sidecar commitid aa25bc3acb2d5546c90def03c31637d36d3c8d49

**Steps to Reproduce**

/accounts/1zpJc8kiUVepY3DVqyGpTV1JPEM7c6aAPTnTcL1RmE75NYM/balance-info
Response:
```
{"at":{"hash":"0xb00b6509d3598cd33f056742a05318b3741c6dfd2f71a17c9c395e6176fb4847","height":"3900889"},"nonce":"3","tokenSymbol":"DOT","free":"9022446388641792000001","reserved":"0","miscFrozen":"0","feeFrozen":"0","locks":[]}
```
free very large.

**Comment by TarikGul** [comment]
Hey @sugeladi.

That is very odd, when reproducing via the endpoint given the response i get is:

```
{"at":{"hash":"0x2292a7630be4a2cec63570311d7a6abccb3b891b53a16dd1539b007d5cb9ecc0","height":"3901190"},"nonce":"3","tokenSymbol":"DOT","free":"2100702000000","reserved":"0","miscFrozen":"0","feeFrozen":"0","locks":[]}
```

I didnt get the same hash, or height, but when i queried those as well, I didn't see any abnormalities. 

Could I get more info as to what version of Sidecar you are running, and any additional info. When you query the same address again do you get the same output?

**Comment by emostov** [comment]
On the Polkadot chain -

query:
```
127.0.0.1:8080/accounts/1zpJc8kiUVepY3DVqyGpTV1JPEM7c6aAPTnTcL1RmE75NYM/balance-info?at=3900889
```

response:
```
{
    "at": {
        "hash": "0xb00b6509d3598cd33f056742a05318b3741c6dfd2f71a17c9c395e6176fb4847",
        "height": "3900889"
    },
    "nonce": "3",
    "tokenSymbol": "DOT",
    "free": "2100702000000",
    "reserved": "0",
    "miscFrozen": "0",
    "feeFrozen": "0",
    "locks": []
}
```

**Comment by sugeladi** [comment]
> Sidecar commit `aa25bc3acb2d5546c90def03c31637d36d3c8d49` against the Polkadot network -
> 
> query:
> 
> ```
> 127.0.0.1:8080/accounts/1zpJc8kiUVepY3DVqyGpTV1JPEM7c6aAPTnTcL1RmE75NYM/balance-info?at=3900889
> ```
> 
> response:
> 
> ```
> {
>     "at": {
>         "hash": "0xb00b6509d3598cd33f056742a05318b3741c6dfd2f71a17c9c395e6176fb4847",
>         "height": "3900889"
>     },
>     "nonce": "3",
>     "tokenSymbol": "DOT",
>     "free": "2100702000000",
>     "reserved": "0",
>     "miscFrozen": "0",
>     "feeFrozen": "0",
>     "locks": []
> }
> ```

You have the same problem with  /balance-info?at=
```
curl --request GET \
>   --url 'http://127.0.0.1:8080/accounts/1zpJc8kiUVepY3DVqyGpTV1JPEM7c6aAPTnTcL1RmE75NYM/balance-info?at=3907317'
{"at":{"hash":"0x76e9e56debff563e6e54dc8d1df04597beefdd46509e6bf60e03918ac3331626","height":"3907317"},"nonce":"3","tokenSymbol":"DOT","free":"9022446388641792000001","reserved":"0","miscFrozen":"0","feeFrozen":"0","locks":[]}
```

But I just retrieved the master code. There is no problem now.
Sidecar commit :75d9cab7477081ac99b344a17c9a0aaf9b286c15
