### ISSUE TITLE
Can a new version be released synchronously on https://hub.docker.com/r/parity/substrate-api-sidecar every time?

### ISSUE THREAD

**Issue by vae520283995** [paritytech/substrate-api-sidecar#456]

**Comment by emostov** [comment]
Starting with https://github.com/paritytech/substrate-api-sidecar/pull/396, a new version should be published to docker hub with each release. The GitHub action to push to docker hub failed for v3.0.5.

Re-running the job now. @TriplEight any insight to why the job failed in the first place? Looks like it was complaining about docker hub credentials.

**Comment by TriplEight** [comment]
I believe that was a bug in the v1 of the github action we use to push images. For some reason, it tried to upload the newly created tag from the registry and fails.
```
/usr/bin/podman pull docker-daemon:substrate-api-sidecar:v3.0.5
  reference does not exist
Error: 1 error occurred:
	* Error initializing source docker-daemon:substrate-api-sidecar:v3.0.5: Error loading image from docker engine: Error response from daemon: reference does not exist
substrate-api-sidecar:v3.0.5 not found in Docker image storage
```

However, the image tagged `v3.0.5` is published now.

**Comment by vae520283995** [comment]
@emostov @TriplEight 
Hello, v4.0.0 is still not published to docker hub synchronously

**Comment by TriplEight** [comment]
fixed in https://github.com/paritytech/substrate-api-sidecar/pull/470, `latest` tag's already updated from that branch.
