### ISSUE TITLE
/blocks/3322531 returns incorrect rebonding amount

### ISSUE THREAD

**Issue by Blueswing** [paritytech/substrate-api-sidecar#462]
**Description**

The endpoint `/blocks/3322531` gives me the following response:

```json
{
"method": {
"pallet": "staking",
"method": "rebond"
},
"signature": {
"signature": "0x225ff462ea9a71a4b2d1164ab635cbb697b3d9731abd4cfd552d28d69258e9725410d5080b4fd13c41ea89712e6b9938e823821aac2b8c5eea6b6baba2016381",
"signer": "1Qk4qQ56Crm2ozBnBiL9rKinKADHKQk9xgKsmmrc6WK1DTM"
},
"nonce": "13",
"args": {
"value": "3704762070000000000"
},
"tip": "0",
"hash": "0x63501cb58cef8059903282e05a4349d8a023dea90ce7c4d11540fe207a19ce1a"
}
```

**Expected vs. Actual Behavior**

I don't think the `args.value` property is correct, because it means **370,476,207 DOT** which is an increditably huge amount. It looks 10000x larger than the expected value. You can find the original unbonded value here: `https://polkascan.io/polkadot/transaction/0xe455c479c3ba833da4e8a3824efc1b6e6cc6b2633eb7c139e5a6cd02d39e7560`

Here is an example of a correct response: `/blocks/4096024`

**Comment by emostov** [comment]
This appears to be decoding the block correctly. The sender did indeed specify a very high value to rebond. 

If we look at the code for `rebond` you will see that it rebonds the unlocking chunks up until the user specified `value`. If the user specified `value` is greater than the sum of the unlocking chunks then it will simply rebond that sum of the unlocking chunks. See the [source code here for details](https://github.com/paritytech/substrate/blob/ac1f7ff32bf0d0e9c328cfe083bee7492c639946/frame/staking/src/lib.rs#L535-L558).

You can see the effects by checking the accounts staking ledger history; checkout the changes to `unlocking` and `active`
- Before rebond tx: `/accounts/1Qk4qQ56Crm2ozBnBiL9rKinKADHKQk9xgKsmmrc6WK1DTM/staking-info?at=3322530`
```json
 "staking": {
        "total": "370476207789663",
        "active": "0",
        "unlocking": [
            {
                "value": "370476207789663",
                "era": "250"
            }
        ],
}
```
- After the rebond tx `/accounts/1Qk4qQ56Crm2ozBnBiL9rKinKADHKQk9xgKsmmrc6WK1DTM/staking-info?at=3322531`
```json
    "staking": {
        "stash": "1Qk4qQ56Crm2ozBnBiL9rKinKADHKQk9xgKsmmrc6WK1DTM",
        "total": "370476207789663",
        "active": "370476207789663",
        "unlocking": [],
```

Additionally, we can go and cross check with some block explorers to confirm `value`:
- https://polkascan.io/polkadot/transaction/0x63501cb58cef8059903282e05a4349d8a023dea90ce7c4d11540fe207a19ce1a
- https://polkadot.subscan.io/extrinsic/3322531-2

**Comment by Blueswing** [comment]
@emostov Thanks! This solved my problem.
