### ISSUE TITLE
Update Staking Endpoints for *30 changes

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/substrate-api-sidecar#468]
https://github.com/paritytech/substrate/pull/8113 will remove the off-chain election and corresponding `Open`, `Closed` statuses. Will need to update the API and docs to handle the new staking API.

Should support the legacy (V5) staking for some period for any parachains that might still be using it.

**Comment by dvdplm** [comment]
Fixed by #485 

(@TarikGul seems like the github AI isn't AI enough to autoclose issues with "resolves issue x"; need to use "fixes x" or "closes x" I think)
