### ISSUE TITLE
Can't run the latest version binary anymore

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate-api-sidecar#487]
After updating to the latest version in a project, I get the following error: 

```
test/node_modules/@polkadot/api/index.js:3
import "./detectPackage.js";
       ^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
```

easy enough to reproduce via

```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "@polkadot/api": "4.2.1",
    "@substrate/api-sidecar": "4.0.1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}

```

followed by `./node_modules/.bin/substrate-api-sidecar  `

**Comment by emostov** [comment]
I think this issue should be resolved by bumping your `node` version to 12 or higher. 
I personally have it working with `node` `v15.2.1`.

**Comment by kianenigma** [comment]
huh leah I haven't updated node in ages, nor have I tried, will report back.

**Comment by kianenigma** [comment]
yeah, fixed
