### ISSUE TITLE
Investigate PLO support

### ISSUE THREAD

**Issue by emostov** [paritytech/substrate-api-sidecar#490]
Issue to track feature ideas related to parachain lease offerings.

Possible features include:
- Crowdloan progress endpoint
- Auction progress endpoint

**Comment by emostov** [comment]
These map pretty closely to the pallets themselves?

Could we do 
- GET `pallets/auctions/progress`
- GET `pallets/crowdloan/para/{paraId}`

It would be nice to reserve the `parachains` resource for future usage of the form `parachains/{paraId}/...`

**Comment by joepetrowski** [comment]
I don't really like the `pallets/` routes. These are still in development, and to some extent we are speculating about the user stories that will develop around them. Right now, the responses map pretty closely to the pallets, but I wouldn't be surprised to get a good use case for "I also want to know about X when I get crowdloan info", or just see some of the pallets refactored.

Auctions, crowdloans, and parachains all relate to "who is (or will be, or is trying to be) in some parachain slot".

I quite like `parachains/{paraId}/crowdloan-info` and the `parachains/{paraId}/...` route in general. At this point though, I think we should mark these routes as "experimental" and make it clear that we can break them without bumping a major Sidecar version.

**Comment by dvdplm** [comment]
What if we had the endpoints actually include `/experimental/` in them? As in `pallets/experimental/crowdloans/…`?

Users often fail to read docs and often get angry when stuff marked "experimental" in the docs move about. Maybe we can try being super-extra-explicit about it?

Dumb idea?

**Comment by dvdplm** [comment]
> It would be nice to reserve the `parachains` resource for future usage of the form `parachains/{paraId}/...`

Strongly agree.

**Comment by dvdplm** [comment]
> * GET `parchains/crowdloans`
> 
> * GET `parachains/{paraId}/crowdloan-info`

This is my preference.

**Comment by emostov** [comment]
> What if we had the endpoints actually include `/experimental/` in them? As in `pallets/experimental/crowdloans/…`?
> 
> Users often fail to read docs and often get angry when stuff marked "experimental" in the docs move about. Maybe we can try being super-extra-explicit about it?
> 
> Dumb idea?

I think this is  great idea. The alternative I was thinking is having a field in the response `message: "This is an experimental endpoint and subject to breaking changes without a corresponding versioning bump"` or even just `experimental: true`

**Comment by emostov** [comment]
I am thinking we should support an endpoint that shows who is winning at any particular point in the ending period.

`GET /parachains/auctions/winning?at=<BlockId>`

```javascript
{
  at: { .. },
  winning: [
    {
       slotRange: 'zeroZero'
       info: { 
         bidder: '1f3ab',
         paraId: '123',
         amount: '1234567890'
       }
     }
   ]
}
```

**Comment by emostov** [comment]
Another one that may be helpful is to directly view deposits for current and future lease periods:

`GET /paras/leases`

```javascript
{
  at: { .. },
  parachains: Array<ParaId>,
  parathreads: Array<ParaId>,
  currentLeaseIndex: '0',
  remainingBlocks: '356746592' // Blocks remaining in lease period
}
```

`GET paras/{paraId}/lease-info`

```javascript
{
  at: { .. },
  leases: [
    {
       leaseIndex: '0',
       account: '1f3ab',
       amount: '1234567890'
    }
  ] 
}
```

**Comment by emostov** [comment]
Since crowdloans can end at a very far point in the future but the auctions they are intended for might end much sooner, we should have a way of mapping crowdloans to auctions they target and if all of those auctions are over make it clear that it no longer needs to be contributed to.

**Comment by joepetrowski** [comment]
Good idea, but check with @shawntabrizi about that because I think the crowdloan logic now might check for that and close those immediately since they are (a) bad UX and (b) taking up state.
