### ISSUE TITLE
failed decoding electionProviderMultiPhase.submitUnsigned

### ISSUE THREAD

**Issue by yasyzb** [paritytech/substrate-api-sidecar#492]
**Description**

{"code":500,"message":"createType(SignedBlock):: Struct: failed on block: {\"header\":\"Header\",\"extrinsics\":\"Vec<Extrinsic>\"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding electionProviderMultiPhase.submitUnsigned:: Struct: failed on args: :: Cannot construct unknown type RawSolution","stack":"Error: createType(SignedBlock):: Struct: failed on block: {\"header\":\"Header\",\"extrinsics\":\"Vec<Extrinsic>\"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding electionProviderMultiPhase.submitUnsigned:: Struct: failed on args: :: Cannot construct unknown type RawSolution\n    at createTypeUnsafe (/usr/src/app/node_modules/@polkadot/types/create/createType.js:72:11)\n    at RpcCore._formatOutput (/usr/src/app/node_modules/@polkadot/rpc-core/index.js:394:41)\n    at callWithRegistry (/usr/src/app/node_modules/@polkadot/rpc-core/index.js:262:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:93:5)","level":"error"}

**Steps to Reproduce**

curl http://127.0.0.1:8080/blocks/4355787

**Expected vs. Actual Behavior**

[A clear description of what you expected to happen and what actually happened.]

**Comment by anhcao142** [comment]
Hi, I encounter the same error

**Comment by emostov** [comment]
I cannot reproduce this issue. How are you installing

I tried v4.0.0, v4.0.1, and v4.0.2 - they all worked for me against `blocks/4355787`.

- Can you double check your api-sidecar version? 
- Can you check the exact version of the `@polkadot` scoped deps it is using (i.e. @polkadot/api, @polkadot/types etc). For the polkadot-js deps you should be able to find them in the `node_modules` folder where api-sidecar is installed; check there packages `package.json` files to see there version directly. Should be `4.2.1` for the latest sidecar.

**Comment by emostov** [comment]
Does the issue resolve if you upgrade to the node to the latest client release?

**Comment by anhcao142** [comment]
I can't reach my server right now. I'll update as soon as possible

**Comment by yasyzb** [comment]
> Does the issue resolve if you upgrade the node to the latest client release?

Thanks, it resolve when I upgrade to v4.0.2. 
(My sidecar version is v3.0.4)

**Comment by anhcao142** [comment]
@emostov Upgrade Polkadot to `0.8.29` and Substrate to `4.0.2` solve the problem for me. My previous version was `0.8.26-rc2`. Kind of weird since the release note doesn't force you to upgrade

**Comment by emostov** [comment]
> @emostov Upgrade Polkadot to `0.8.29` and Substrate to `4.0.2` solve the problem for me. My previous version was `0.8.26-rc2`. Kind of weird since the release note doesn't force you to upgrade

@anhcao142 what version of Sidecar where you on before? Just trying to figure out if it was upgrading Sidecar that fixed it or upgrading the node

**Comment by anhcao142** [comment]
It's 3.0.4. Hope that help

**Comment by Blueswing** [comment]
I have the same problem at block 4355787. My sidecar version was `v3.0.4` and the problem was solved by upgrading it to `v4.0.4`.
