### ISSUE TITLE
Script to test queries across multiple runtimes, and different blocks

### ISSUE THREAD

**Issue by TarikGul** [paritytech/substrate-api-sidecar#495]
**Proposed Change or Idea**

I wrote an example as to what it would look like [here](https://github.com/TarikGul/sidecar-runtime-test). Every time we push out a new release we have to test sidecar manually against chains such as 'Polkadot', 'Kusama', 'westend' and make sure there are no errors across many types of transactions and runtimes. We might find something like this useful, whether we want to integrate it in Sidecar or use it as an external helper script. 

Things that could be updated with it. A arg parser to determine which chain we want to test against, and a bash script to automate it all. In the example I have it working with Polkadot.

**Comment by dvdplm** [comment]
Maybe something we can have CI do for us?

**Comment by TarikGul** [comment]
Yea I will open up an issue with the CI team, and see what kind of thoughts they have on this.

**Comment by dvdplm** [comment]
Maybe we could leverage the WASM runtime override feature that @insipx added for `substrate-archive`, and maybe even the library of wasm blobs maintained there?

**Comment by TarikGul** [comment]
Now that the [sidecar-runtime-test](https://github.com/TarikGul/sidecar-runtime-test) is working well, and is used frequently per release, I will clean it up and work on making it a `paritytech` repo. For now I think it's better to have it as a helper library instead of integrated into sidecar because it requires Sidecar to be in either dev mode, or built and then ran.
