### ISSUE TITLE
Create storage keys directly from expanded metadata

### ISSUE THREAD

**Issue by emostov** [paritytech/substrate-api-sidecar#528]
**Proposed Change or Idea**

In  #383 we use the API to get all known storage keys. However, the API likely uses only the most up to data metadata for the runtime. Instead we should get the metadata of the runtime for the respective query and make the keys off of that.

Here is what we currently do

```javascript
function getKeyNames(api: ApiPromise): Record<string, KeyInfo> {
	const moduleKeys = Object.keys(api.query).reduce((acc, mod) => {
		Object.keys(api.query[mod]).forEach((item) => {
			const queryObj = api.query[mod][item];
			let key;
			try {
				// Slice off '0x' prefix
				key = queryObj.key().slice(2);
			} catch {
				key = queryObj.keyPrefix().slice(2);
			}

			acc[key] = {
				module: mod,
				item,
			};
		});

		return acc;
	}, {} as Record<string, KeyInfo>);
```

Instead ok keying in `api.query` and using the decorated keys, we should probably just loop through the metadata create the storage keys based off that.

**Comment by emostov** [comment]
Can probably look into using the decorate storage from polkadot-js https://github.com/polkadot-js/api/blob/a1f07e32743eed1c27bf06ca6fb9118afdbfa839/packages/metadata/src/decorate/storage/index.spec.ts#L14

**Comment by TarikGul** [comment]
Hmmm, I think this could be another reason for a potential metadata archive helper library.
