### ISSUE TITLE
Reduce controller config boilerplate

### ISSUE THREAD

**Issue by emostov** [paritytech/substrate-api-sidecar#544]
Ideally we should just state which controllers we want and assume that all controllers not explicitly mentioned are not available. So it'd be `controllers = [Blocks, BlocksExtrinsics, AccountAssets, …, …];`. The controllers for kilt, dock, kulupu etc are getting pretty boilerplatey.

_Originally posted by @dvdplm in https://github.com/paritytech/substrate-api-sidecar/pull/533#discussion_r629967716_

**Comment by TarikGul** [comment]
Tackling this today.
