### ISSUE TITLE
`/blocks` endpoint did not include events polkadot#4880032 

### ISSUE THREAD

**Issue by emostov** [paritytech/substrate-api-sidecar#548]
In at least one instance the blocks endpoint does not return events with a block but also does not include any indication that the lack of events is an error; instead the events field is simply an empty array.

The reported error happened 3898 blocks after a runtime upgrade. The error was on polkadot block 4880032 and the v30 runtime upgrade was on block 4876134. The v30 runtime upgrade had a massive migration for the the `AccountInfo` storage item, causing  some parts of the network to lag for ~70 minutes afaik. According to subscan.io the runtime upgrade block was dated at UTC 16:53:06 while the problematic block is dated at UTC 00:46:36.

My suspicion is the that storage RPC call for events returned no events, but did not error.

Ideally Sidecar should have a message that it expected events but the node did not return any. We currently have a similar message for when the RPC fails: 

https://github.com/paritytech/substrate-api-sidecar/blob/bf47b11cdbbe4e40c147878243c11c99b77f3a9d/src/services/blocks/BlocksService.ts#L608-L612

**Comment by emostov** [comment]
[current_block_response.txt](https://github.com/paritytech/substrate-api-sidecar/files/6479970/current_block_response.txt)
[problematic_block_during_runtime.txt](https://github.com/paritytech/substrate-api-sidecar/files/6479971/problematic_block_during_runtime.txt)

**Comment by panlilu** [comment]
+1

**Comment by kmur911** [comment]
+1 experienced this same thing

**Comment by emostov** [comment]
We could potentially just provide a message every time the events array is empty, but we should first investigate if with Substrate FRAME we could ever expect an extrinsic to have 0 events. If there is a case where 0 events are expected we may need some more complex logic to determine if there was an error.

**Comment by TarikGul** [comment]
This is a no longer an issue, and closing.
