### ISSUE TITLE
GET on /blocks/head with connected Kusama node returns an error 500

### ISSUE THREAD

**Issue by CrommVardek** [paritytech/substrate-api-sidecar#552]
**Description**

I've set up a Kusama Node on a docker container and a sidecar API connected to the node (docker as well)

Details of the docker-compose file : 

`
version: "3.8"
services: 
    kusama-node: 
        image: parity/polkadot:v0.9.1
        volumes: 
            - kusama-node:/var/lib/kusama/node
        container_name: Kusama_Node
        command: '--name "CrommVardekNode" --chain kusama --unsafe-ws-external --rpc-cors=all'
    sidecar:
        image: parity/substrate-api-sidecar:latest
        container_name: Kusama_sidecar
        ports:
            - "127.0.1.1:8080:8080"
        environment:
            SAS_SUBSTRATE_WS_URL: ws://kusama-node:9944

volumes:
  kusama-node:
    external: true    
`

Both starts properly, and sidecar is able to connect to the kusama-node. (GET on /runtime/specs returns code 200)

**Steps to Reproduce**

Http GET on http://127.0.1.1:8080/blocks/head

returns 

{"code":500,"message":"Cannot read property 'extrinsicBaseWeight' of undefined","stack":"TypeError: Cannot read property 'extrinsicBaseWeight' of undefined\n    at BlocksService.createCalcFee (/usr/src/app/build/src/services/blocks/BlocksService.js:319:61)\n    at processTicksAndRejections (node:internal/process/task_queues:94:5)\n    at async BlocksService.fetchBlock (/usr/src/app/build/src/services/blocks/BlocksService.js:84:35)\n    at async BlocksController.getLatestBlock (/usr/src/app/build/src/controllers/blocks/BlocksController.js:105:49)\n    at async /usr/src/app/build/src/controllers/AbstractController.js:159:9","level":"error"}

**Expected vs. Actual Behavior**

Excepted a 200 return code with the details of the head block.

**Comment by TarikGul** [comment]
Hey, @CrommVardek . Thanks for reporting the issue. 

Can you confirm with me the version of Sidecar you are using. 

We just released `v6.2.0` yesterday which fixes issues with decoding validator election solutions that prevented certain blocks from being decoded on Polkadot and Kusama. By the looks of it, you might have been running your container before the release which would be using ` <= v6.1.0`.

Also it would be a big help if you knew exactly what block the head was when you were running the request. Currently I am not able to reproduce the issue as it is working on my end, but with the exact block number It would help us test against the specific block itself and hopefully find any bugs if they exist.

**Comment by CrommVardek** [comment]
It was indeed v.6.1.0 I was using.

I re-started the API and I do have a 200 response on /blocks/head, so the issue is no longer an issue ! 

Thanks @TarikGul
