### ISSUE TITLE
Kusama get block /blocks/7511524 timeout

### ISSUE THREAD

**Issue by panlilu** [paritytech/substrate-api-sidecar#558]
**Description**

Kusama get block /blocks/7511524 timeout
Not all of blocks have this problem, but this is not the only example that has this problem.

System: Ubuntu 18.04.3 LTS (GNU/Linux 5.0.0-1025-gcp x86_64)
polkadot version: v0.9.2-f36bb8201-x86_64-linux-gnu
substrate-api-sidecar version: v6.2.0

**Steps to Reproduce**

curl http://127.0.0.1:8080/blocks/7511523 (Works fine)
curl http://127.0.0.1:8080/blocks/7511524 (Timeout)

sidecar error log
```
 error: RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage system.events:: createType(Vec<EventRecord>):: Vec length 463480160424077428963507776117503744973689079580904226164820062076774501249508840588260143653042117102035059634721982563170465997379086 exceeds 65536
```

**Comment by emostov** [comment]
I can't reproduce the issue.

What happens when you run:

```bash
curl -o /dev/null -s -w 'Establish Connection: %{time_connect}s\nTTFB: %{time_starttransfer}s\nTotal: %{time_total}s\n' http://127.0.0.1:8080/blocks/7511524
```

The endpoint is working for me and I get the following when I run the above:

```bash
Establish Connection: 0.000313s
TTFB: 1.010268s
Total: 1.010463s
```

**Comment by panlilu** [comment]
My own fault.
Because of some code imported for support ChainX.
Issue closed.
