### ISSUE TITLE
Ubuntu. Not install

### ISSUE THREAD

**Issue by tryexceptend** [paritytech/substrate-api-sidecar#564]
Hi. I can't install it.
:~$ npm install @substrate/api-sidecar
npm WARN deprecated @types/yaml@1.9.7: This is a stub types definition. yaml provides its own type definitions, so you do not need this installed.
npm WARN enoent ENOENT: no such file or directory, open '/home/polkadot/package.json'
npm WARN @polkadot/util-crypto@5.9.2 requires a peer of @polkadot/util@5.9.2 but none is installed. You must install peer dependencies yourself.
npm WARN polkadot No description
npm WARN polkadot No repository field.
npm WARN polkadot No README data
npm WARN polkadot No license field.

npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /home/polkadot/node_modules/@substrate/api-sidecar/build/src/main.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/polkadot/node_modules/@substrate/api-sidecar/build/src/main.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/polkadot/.npm/_logs/2021-05-27T06_36_37_375Z-debug.log

**Comment by Swader** [comment]
Same issue here.

Manual build fails at:

![image](https://user-images.githubusercontent.com/1430603/119781649-8db4b180-becb-11eb-914c-7b1134dfe25a.png)

**Comment by TarikGul** [comment]
@tryexceptend @Swader Thanks for posting this issue looking into it right now.

**Comment by TarikGul** [comment]
@Swader Do you get the same error when using the command `yarn build`?

**Comment by Swader** [comment]
No, that command is silent (no output).

**Comment by TarikGul** [comment]
So it should be silent, meaning if there is no output on the terminal it was successful and worked. 

The reason I ask, is when launching `tsc` there is a possibility it's pulling from your global packages not the local dependencies, which could be a different version of typescript than what we are using which could potentially cause an error like this.

Currently on `master` or tag `v6.2.1` I am able to `yarn build` then `yarn start` with no issues.

**Comment by Swader** [comment]
Sure but it's not producing a binary, and installing sidecar with yarn add @substrate/api-sidecar does also not produce a .bin file

**Comment by TarikGul** [comment]
Thanks for your patience. We just released v6.2.3 which solves this issue. You should now be able to pull down `@substrate/api-sidecar` without any build errors. 

The issue was quite subtle and I am glad we found it relatively quick but as a quick explanation, the machine from where release 6.2.1, and 6.2.2 were pushed out of had an npm version <  7 which was causing the build to not be present within the npm registry. 

Let me know if this clears the issue for you!

**Comment by TarikGul** [comment]
> Sure but it's not producing a binary, and installing sidecar with yarn add @substrate/api-sidecar does also not produce a .bin file

Sorry about that I misunderstood the context there. But yea, as mentioned above the package should now work. :)

**Comment by Swader** [comment]
All fixed, thank you!

**Comment by Swader** [comment]
@TarikGul perhaps related, but I cannot get sidecar to connect now

![image](https://user-images.githubusercontent.com/1430603/119876860-a0110880-bf28-11eb-89a0-0d9e243e9f8d.png)

**Comment by Swader** [comment]
Documented here: https://github.com/paritytech/substrate-api-sidecar/issues/568

**Comment by TarikGul** [comment]
Awesome thanks will bring the conversation there as this is a seperate issue.

**Comment by tryexceptend** [comment]
Thank you! Installation is ok!

**Comment by TarikGul** [comment]
Closing issue due to being resolved.
