### ISSUE TITLE
GET on /accounts/accountId/asset-balances with connected Westend node returns an error 500

### ISSUE THREAD

**Issue by qinheqing** [paritytech/substrate-api-sidecar#569]
env：
Polkadot v0.9.3
substrate-api-sidecar 6.2.3
Westend

`http://127.0.0.1:8080/accounts/5CMFCMU2wEbs6hCX7B2chU9yQMYxuiJiJxbQg6Nx97VAaYtX/asset-balances`

`{
    "code": 500,
    "message": "Cannot read property 'asset' of undefined",
    "stack": "TypeError: Cannot read property 'asset' of undefined\n    at AccountsAssetsService.fetchAssetBalances (/usr/lib/node_modules/@substrate/api-sidecar/build/src/services/accounts/AccountsAssetsService.js:24:49)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async AccountsAssetsController.getAssetBalances (/usr/lib/node_modules/@substrate/api-sidecar/build/src/controllers/accounts/AccountsAssetsController.js:61:57)\n    at async /usr/lib/node_modules/@substrate/api-sidecar/build/src/controllers/AbstractController.js:159:9",
    "level": "error"
}`

**Comment by emostov** [comment]
Westend doesn't have the assets pallet afaik. @TarikGul we should take the endpoint out of the controller config?

**Comment by TarikGul** [comment]
Yea lets take it off of westend, polkadot, and kusama, and the default controller. While we are at it should we add a statetmint config as well?

**Comment by emostov** [comment]
Yup, makes sense to me
