### ISSUE TITLE
kusuma network， balance-info error

### ISSUE THREAD

**Issue by debuggor** [paritytech/substrate-api-sidecar#580]
curl -s http://0.0.0.0:8879/accounts/F4xQKRUagnSGjFqafyhajLs94e7Vvzvr8ebwYJceKpr8R7T/balance-info

{"code":500,"message":"Unable to decode storage balances.locks:: createType(WeakVec):: Cannot construct unknown type WeakVec","stack":"Error: Unable to decode storage balances.locks:: createType(WeakVec):: Cannot construct unknown type WeakVec\n    at RpcCore._newType (/usr/src/app/node_modules/@polkadot/rpc-core/index.cjs:457:13)\n    at RpcCore._formatStorageData (/usr/src/app/node_modules/@polkadot/rpc-core/index.cjs:391:17)\n    at RpcCore._formatOutput (/usr/src/app/node_modules/@polkadot/rpc-core/index.cjs:368:19)\n    at callWithRegistry (/usr/src/app/node_modules/@polkadot/rpc-core/index.cjs:247:42)\n    at processTicksAndRejections (node:internal/process/task_queues:94:5)","level":"error"}

**Comment by TarikGul** [comment]
Hey @debuggor,

Using sidecar v7.0.0 I am able to query the above path successfully.

```
{"at":{"hash":"0xa4191ba9cf0cab564d39da6ab01313db0e0e7d74def9cb46ce16f16457971e5b","height":"7824368"},"nonce":"33031","tokenSymbol":"KSM","free":"266433660982038864","reserved":"0","miscFrozen":"0","feeFrozen":"0","locks":[]}
```

I wasn't able to reproduce your issue above. What version of Sidecar are you running?

**Comment by debuggor** [comment]
![image](https://user-images.githubusercontent.com/30191281/121180669-ae014a80-c893-11eb-9a23-2851d0d86f7b.png)

**Comment by debuggor** [comment]
Do I need to configure "SAS_SUBSTRATE_TYPES", how do I configure it, thanks

**Comment by TarikGul** [comment]
Okay cool, I was able to reproduce it using the global substrate-api-sidecar package. Seems like there is some type issues happening in the packaging through the NPM registry.

```JSON
{"code":500,"message":"Unable to decode storage balances.locks:: createType(WeakVec):: Cannot construct unknown type WeakVec","stack":"Error: Unable to decode storage balances.locks:: createType(WeakVec):: Cannot construct unknown type WeakVec\n    at RpcCore._newType (/Users/tarik/.nvm/versions/node/v14.15.0/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/rpc-core/index.cjs:457:13)\n    at RpcCore._formatStorageData (/Users/tarik/.nvm/versions/node/v14.15.0/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/rpc-core/index.cjs:391:17)\n    at RpcCore._formatOutput (/Users/tarik/.nvm/versions/node/v14.15.0/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/rpc-core/index.cjs:368:19)\n    at callWithRegistry (/Users/tarik/.nvm/versions/node/v14.15.0/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/rpc-core/index.cjs:247:42)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","level":"error"}
```

For now, a work around would be to pull the package down from master, and then build it locally and run it. 

```
git clone https://github.com/paritytech/substrate-api-sidecar.git
cd substrate-api-sidecar
yarn
yarn build
export SAS_SUBSTRATE_WS_URL=wss://kusama-rpc.polkadot.io
yarn start
```

Going to work on a fix right away. Thank you for publishing the issue.

**Comment by debuggor** [comment]
master, local compilation, solved, thanks
