### ISSUE TITLE
CI: workflow to test and check the global substrate-api-sidecar package

### ISSUE THREAD

**Issue by TarikGul** [paritytech/substrate-api-sidecar#581]
There have been a few instances when releasing substrate-api-sidecar that the package's bin either doesn't exist (this is caused by releasing from a machine that has npm --version < 7), or missing types from the packaging (see this issue [#580](https://github.com/paritytech/substrate-api-sidecar/issues/580)). 

It could be a great idea to automate a simple CI e2e test against the global package every time we have a new release.

**Comment by TarikGul** [comment]
As a sidenote as well [#580](https://github.com/paritytech/substrate-api-sidecar/issues/580) was not a global package issue but a `@polkadot/4.12.1` issue with v7.0.0 of sidecar. This could have been caught in the e2e tests if we were also testing against the accounts endpoint. 

Need to look into why the `WeakVec` type was not caught inside of the unit tests either.

**Comment by emostov** [comment]
`WeakVec` is new I think? 

Probably good to add a test case for `WeakVec` to `sanitizeNumbers.spec`.

**Comment by TarikGul** [comment]
`WeakVec<Type>` is actually just converted to `Vec<Type>` in polkadot-js so we'll never see it exposed as a return type via the api. 

In addition I think this test might be unnecessary given the workflow we have gotten into for publishing. Going to close this issue for now, but something like this could be possible but I don't see its need as essential anymore.
