### ISSUE TITLE
Getting `Fee calculation not supported for this network` on local node

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/substrate-api-sidecar#583]
I am running node on local. I tried to transfer balance from one account to another and wanted to know exact transaction fee. 

I followed all steps and hit this query `curl -s http://0.0.0.0:8080/blocks/0xf487de8813810f4c4bac9e7a5ece4cf3fb9594eb7687cb1d7fd1f3dbeb8273c8`

But getting below response 

`{"number":"130","hash":"0xf487de8813810f4c4bac9e7a5ece4cf3fb9594eb7687cb1d7fd1f3dbeb8273c8","parentHash":"0xe221851c2ba12aca4c3e9303c04469866cd8baa62869426a2fdb5d247c0c3ffc","stateRoot":"0x3111a59e1c118616647c641a7d2a62ba76ca7fcc7ac9998d6a49357afe2e6f29","extrinsicsRoot":"0xc41dc59ea9afc565792787ac8eb092894746922e716dad2e8992068f84f9466a","authorId":"4NHNWXXLvDHpnDqKCa67zHU8iQyAQrs7wZxBucyXdeGWS4R3","logs":[{"type":"PreRuntime","index":"6","value":["0x42414245","0x020000000020ff661600000000"]},{"type":"Seal","index":"5","value":["0x42414245","0x4693bce8ef6007261093c7aa10f4cda469a2a020082a2a04f84f73901c04410be08db1c59a14bfc20832ac1cfd411f149b6c1984451498981f9fb2eccf16b682"]}],"onInitialize":{"events":[]},"extrinsics":[{"method":{"pallet":"timestamp","method":"set"},"signature":null,"nonce":null,"args":{"now":"1623666539520"},"tip":null,"hash":"0x267d441a1f6fc21db353ea42bdc1a3502ec4c92896178f7e7a2fa2022ef439f2","info":{},"events":[{"method":{"pallet":"system","method":"ExtrinsicSuccess"},"data":[{"weight":"161650000","class":"Mandatory","paysFee":"Yes"}]}],"success":true,"paysFee":false},{"method":{"pallet":"balances","method":"transfer"},"signature":{"signature":"0xf6089ec7e2e34e49fc78abc4e3f640473e269a3dbda7ace10129fa965e0a2448d1a5968fece6b8b8e79fd1caef46543afe1cf953cda9d49917f5e8f1f6f4a584","signer":{"id":"4Nn1beMcdNf3cZcp14hCR77cFjvEjmd8gBiLfEpfdauwP1KB"}},"nonce":"0","args":{"dest":{"id":"4PBoBEmcm3Nf6sEZ6ciH5uy47cjtPi6DEDpRhQpVZPnMwTWi"},"value":"1000000000000000"},"tip":"0","hash":"0x50656988701568273f34488482591c113d3085bf1f0e3c9b7c356c41d31d83c6","info":{"error":"Fee calculation not supported for this network"},"events":[{"method":{"pallet":"system","method":"NewAccount"},"data":["4PBoBEmcm3Nf6sEZ6ciH5uy47cjtPi6DEDpRhQpVZPnMwTWi"]},{"method":{"pallet":"balances","method":"Endowed"},"data":["4PBoBEmcm3Nf6sEZ6ciH5uy47cjtPi6DEDpRhQpVZPnMwTWi","1000000000000000"]},{"method":{"pallet":"balances","method":"Transfer"},"data":["4Nn1beMcdNf3cZcp14hCR77cFjvEjmd8gBiLfEpfdauwP1KB","4PBoBEmcm3Nf6sEZ6ciH5uy47cjtPi6DEDpRhQpVZPnMwTWi","1000000000000000"]},{"method":{"pallet":"treasury","method":"Deposit"},"data":["1184280500179"]},{"method":{"pallet":"system","method":"ExtrinsicSuccess"},"data":[{"weight":"225698000","class":"Normal","paysFee":"Yes"}]}],"success":true,"paysFee":true}],"onFinalize":{"events":[]},"finalized":true}`

Please let me know what I am missing here

**Comment by niklasad1** [comment]
Hey,

Can you please specify which network you are running the local node on and the version please?

**Comment by ayushmishra2005** [comment]
I am using Substrate 3.0.3 and running node on local

**Comment by TarikGul** [comment]
@ayushmishra2005 Can you also expand on the CLI command you are running to run the node locally.

**Comment by ayushmishra2005** [comment]
> @ayushmishra2005 Can you also expand on the CLI command you are running to run the node locally.

Sorry I didn't understand your question. I already mentioned in my question. I am hitting this command `curl -s http://0.0.0.0:8080/blocks/0xf487de8813810f4c4bac9e7a5ece4cf3fb9594eb7687cb1d7fd1f3dbeb8273c8`

**Comment by niklasad1** [comment]
@ayushmishra2005 

The question is how you run your local node,  such as 

```$ substrate --chain dev <other flags>```

Otherwise, we don't know how to reproduce this.

**Comment by ayushmishra2005** [comment]
./target/release/node-template \
  --base-path /tmp/polkadot-chains/alice \
  --name "Development Chain" \
  --dev \
  --telemetry-url "wss://telemetry.polkadot.io/submit/ 0" \
  -lruntime=debug

**Comment by TarikGul** [comment]
Awesome so given what you showed me I can tell you this is expected behavior when using the node-template. 

In Sidecar we recognize that all chains do not calculate fees, therefore we cache and store block weights depending on a chains specName. In this case because the specName for the node you are running is `node-template` (which is a specName we do not recognize in sidecar) you will get the following error `Fee calculation not supported for this network`. 

A list of specName's we recognize for calculating fees can be found [here](https://github.com/paritytech/substrate-api-sidecar/blob/master/src/chains-config/metadata-consts/index.ts#L69).

**Comment by ayushmishra2005** [comment]
Thanks for clarifying it. @TarikGul
