### ISSUE TITLE
Update auction endpoints (track paritytech/polkadot/pull/3346)

### ISSUE THREAD

**Issue by emostov** [paritytech/substrate-api-sidecar#588]
https://github.com/paritytech/polkadot/pull/3346 will have some updates to the how the auctions are exposed. Some logic in the auction endpoints will likely need to get tweaked and will need changes to reflect the new `AuctionStatus` enum

**Comment by TarikGul** [comment]
Awesome just saw that it got merged into master, and is going in the next runtime upgrade. Thanks!

**Comment by TarikGul** [comment]
[591](https://github.com/paritytech/substrate-api-sidecar/pull/591) closes this.

**Comment by TarikGul** [comment]
Prematurely closed this issue, and confused it with another. Reopening.
