### ISSUE TITLE
Add ESlint

### ISSUE THREAD

**Issue by emostov** [paritytech/substrate-api-sidecar#61]
I would like to advocate for adding ESLint to `sidecar`. With plans to add significant test coverage (and the necessary refactorizations) in the near future plus a growing, diverse group of contributors, it would behoove `sidecar`’s maintainers to add a linter. My proposal would be to closely mimic @amaurymartiny ESLint setup in `txwrapper` because 1) the repos are intended to be used together & 2) since @amaurymartiny is well experienced in JS work at Parity and frequently reviews this repo we could benefit from his consultation in config decisions/ justification.

Benefits would include
- Static syntax checking
- Style checking to help contributors conform to style guidelines
- Hopefully encourage more idiomatic and safer code

I would personally be happy to do the setup of ESLint in the repo. Before starting though I would like to get feedback/ advice from stakeholders and frequent reviewers, including @amaurymartiny, @danforbes, @joepetrowski, &  @maciejhirsz.

**Comment by danforbes** [comment]
Thanks for opening this, @emostov! If possible, I would like to use #47 as our branch for this, just since it is already there. I will get that branch in a good state but feel free to let me know if you have other plans.
