### ISSUE TITLE
e2e python script needs some work.

### ISSUE THREAD

**Issue by TarikGul** [paritytech/substrate-api-sidecar#611]
Few things need to be added to that script or changed.

1. Read the output of sidecar, and when the proper logging is logged, then we can move forward instead of the hardcoded 30 second timeout.

2. Log the STDOUT

3. Wrap the main script in a try catch.

4. Catch kill signals (ctrl+c)

**Comment by jsdw** [comment]
And potentially: catch kill signals (ctrl+c) and kill running processes then also if needbe?

I wonder whether there's a smarter way to have the processes clean up after themselves; it'd be ideal if it just happened pretty automatically.

**Comment by TarikGul** [comment]
Thanks missed the catck kill signals, just added it. 

> I wonder whether there's a smarter way to have the processes clean up after themselves; it'd be ideal if it just happened pretty automatically.

I agree that it should be as easy and smooth as one command, and there shouldn't be any unexpected results.
