### ISSUE TITLE
GET /blocks/head is super slow, add alternative GET /blocks/head/summary

### ISSUE THREAD

**Issue by ngallagher** [paritytech/substrate-api-sidecar#612]
**Proposed Change or Idea**

The /blocks/head method is really slow, it takes forever. Given that the polkadot blockchain mines blocks so quickly it would be nice if you could poll to check where the latest block is frequently without downloading data which may not be interesting.

I would suggest two additional methods.

***Existing***

GET /blocks/head
GET /blocks/:number

***Update***

GET /blocks/head
GET /blocks/head/summary
GET /blocks/:number
GET /blocks/:number/summary

For instance something like the following offers useful information for applications following the progress of the blockchain, without all of the other perhaps less interesting information (depending on requirements)

```
	async fetchBlockSummary(targetHash?: BlockHash): Promise<IBlockSummary> {
		const { api } = this;
		const signedBlock = (targetHash ? await api.rpc.chain.getBlock(targetHash) : await api.rpc.chain.getBlock())
		const block = signedBlock?.block;
		const {
			hash,
			parentHash,
			number,
			stateRoot,
			extrinsicsRoot,
		} = block?.header;			

		return {
			number,
			hash,
			parentHash,
			stateRoot,
			extrinsicsRoot
		};
	}
```

**Comment by TarikGul** [comment]
Yea the `/blocks/head` unfortunately does take some to complete a request, especially if there is a lot of data to parse through and format. I would be interested in putting something like this together, get a branch up, and some benchmarks to see what kind of performance upgrade something like this would yield as well. 

cc: @joepetrowski @emostov @dvdplm 

Any thoughts?

**Comment by joepetrowski** [comment]
Sounds reasonable to me.

**Comment by ngallagher** [comment]
Another idea is perhaps use an LRU cache to avoid repeating the heavy RPC calles for GET /blocks/head, as long as it does not change the behaviour.

**Comment by emostov** [comment]
Yeah, endpoint for just the header sounds reasonable.

But I do think there are probably some easy optimizations we can add in with query params to filter out some fields like block author, finality, and even skipping the events query.

I made an issue for documenting how to improve endpoint performance just with pre-existing query params: https://github.com/paritytech/substrate-api-sidecar/issues/489

**Comment by emostov** [comment]
> Another idea is perhaps use an LRU cache to avoid repeating the heavy RPC calles for GET /blocks/head, as long as it does not change the behaviour.

This sounds worth investigating. Are you thinking of situations where the user polls `blocks/head`?

**Comment by TarikGul** [comment]
> Another idea is perhaps use an LRU cache to avoid repeating the heavy RPC calles for GET /blocks/head, as long as it does not change the behaviour.

Yea this can hold some merrit. The set size of the cache can be really small too. 

@emostov Yea the only instance I can see this being useful is if one is polling `/blocks/head` and the next block has not yet been finalized and the same block ends up getting hit. It could be as simple as just storing the hash of the block, and comparing it to each `hash` param inputted into `fetchBlock`. I would also say that the size of the hash would probably only need to be 1 or 2 as well.

**Comment by emostov** [comment]
> @emostov Yea the only instance I can see this being useful is if one is polling `/blocks/head` and the next block has not yet been finalized and the same block ends up getting hit. It could be as simple as just storing the hash of the block, and comparing it to each `hash` param inputted into `fetchBlock`. I would also say that the size of the hash would probably only need to be 1 or 2 as well.

Yeah I agree, basically just thinking store the last 1 or 2 blocks. I think though if this header query is super fast, you could poll the header and then just get the block once you see a new header.

**Comment by TarikGul** [comment]
Cool. Ill work on getting a draft up, considering it's an extension of the already built `fetchBlock`, It should be pretty trivial.

**Comment by TarikGul** [comment]
@ngallagher So now you can query the header of the latest head, or any block height, which drastically increases the response time for "summary" information on a block.
