### ISSUE TITLE
[Question] What is Substrate's FRAME framework?

### ISSUE THREAD

**Issue by paulvi** [paritytech/substrate-api-sidecar#656]
1) What is Substrate's FRAME framework?

2) Is this summary good? https://github.com/w3f/polkadot-wiki/pull/2550

> **Polkadot-JS RPC** is JavaScript library for interacting with **Substrate RPC API** endpoint, distributed as `@polkadot/api` Node.js package.  
> **Substrate API Sidecar** is using **Polkadot-JS RPC** to provide separately runnable REST service.

3) Is it correct to say, that **Substrate API Sidecar** functionality is fully depend on **Polkadot-JS RPC**/**Polkadot-JS RPC**, and it is not using any other endpoints.

**Comment by TarikGul** [comment]
Hey @paulvi thanks for the question,

1) To keep it simple its a framework for building distributed and decentralized systems. "It is both a library for building new blockchains and a "skeleton key" of a blockchain client, able to synchronize to any Substrate-based chain." - Check [this](https://github.com/paritytech/substrate/tree/master/docs#2-description) out for a great description and some added links, specifically [this blog post](https://www.parity.io/what-is-substrate/) as well. 

2) Yea for how breif of a summary it is I think its alright, `@polkadot/api` is a library focused on exposing a public api to interact with Polkadot and Substrate based nodes (Chains built upon substrate). Sidecar uses the `@polkadot/api` package to expose a REST api for users. So you got that right for sure.

3) As an express framework, yes it is completely reliant on polkadot-js. Sidecar is regularly updated alongside polkadot-js patches and updates so substrate based, or chain specific types are always up to date.

**Comment by paulvi** [comment]
Thanks.

1. From FRAME https://github.com/paritytech/substrate/blob/master/docs/README.adoc is a reference, as blog post https://www.parity.io/blog/what-is-substrate/ does not mention it at all.

It seems that FRAME are 3-4 core modules as on
https://github.com/paritytech/substrate/blob/master/docs/README.adoc#8-documentation

![image](https://user-images.githubusercontent.com/1614482/132157613-5eb9cdb3-2a09-4455-8e0e-cf59f386d744.png)

**Comment by dvdplm** [comment]
@paulvi as Tarik explained, FRAME is a part of `substrate` so best move the followup question over there. :)

**Comment by niklasad1** [comment]
Indeed, but to help you a little bit https://substrate.dev/docs/en/knowledgebase/runtime/frame

Please read the README in substrate and you would find the documentation
