### ISSUE TITLE
[Question] How to generate API docs /dist/ ?

### ISSUE THREAD

**Issue by paulvi** [paritytech/substrate-api-sidecar#669]
How to generate docs that like at https://paritytech.github.io/substrate-api-sidecar/dist/?

I tried `yarn build:docs`
but `dist` folder did not appear after builld.

My understanding is that https://paritytech.github.io/substrate-api-sidecar/dist/ is the latest docs
and for any older release, I should try building from source.

**Comment by paulvi** [comment]
OK, I found that `docs/dist/app.bundle.js` is not generated but updated together with `docs/src/openapi-v1.yaml`

It is still unclear how this `app.bundle.js` is produced.

Please extend `docs/README.md`

https://github.com/paritytech/substrate-api-sidecar/blob/master/docs/README.md

**Comment by TarikGul** [comment]
I just updated the readme inside of the docs to help contribute and generate the `dist` folder. 

running the script `yarn build:docs` will generate and update the docs.

**Comment by paulvi** [comment]
ref #672 

> After updating the docs, ensure to run `yarn build:docs` from the root directory of this repository.

As I saw, command should be run from `docs/` folder,
as `docs` is kind of independent node.js project with its own `package.json`

P.S. found... in root `package.json`

> "build:docs": "(cd docs && yarn && yarn build)",

that may leave user unaware that current project has changed, so that next `yarn` command will be for docs project....


> I tried `yarn build:docs`
> but `dist` folder did not appear after build.

So it will be `docs/dist`
