### ISSUE TITLE
openAPI version is to follow substrate-api-sidecar version, e.g. 1.0.0-v9.1.9

### ISSUE THREAD

**Issue by paulvi** [paritytech/substrate-api-sidecar#670]
**Proposed Change or Idea**

openAPI version is to follow substrate-api-sidecar version

https://github.com/paritytech/substrate-api-sidecar/blame/master/docs/src/openapi-v1.yaml#L11

visible to all at https://paritytech.github.io/substrate-api-sidecar/dist/ as version on grey cloud

![image](https://user-images.githubusercontent.com/1614482/133544727-f77f0c20-6a68-4c0f-a0b0-fad5ec20ab8d.png)

e.g. for current substrate-api-sidecar version `v9.1.9` openAPI version may be like `1.0.0-v9.1.9`

**Alternatives**

Currently, there is no quick way to judge if and when API was change, just by looking at https://paritytech.github.io/substrate-api-sidecar/dist/

**Additional Information**

no

**Comment by TarikGul** [comment]
Thanks for opening up this issue. I just opened up a PR to adjust the version and I also updated the release docs to make sure upon each release we also update the version in the docs. 

> Currently, there is no quick way to judge if and when API was change

I would say the best source of truth for this is to track/watch the github tags, and releases.
