### ISSUE TITLE
Port over all api.query.<pallet>.<method>.at() -> api.at() historic api

### ISSUE THREAD

**Issue by TarikGul** [paritytech/substrate-api-sidecar#698]
All services that use api.query.<pallet>.<method>.at() will be deprecated via [affa6ab](https://github.com/polkadot-js/api/commit/affa6ab1bd19b7819766fd8015f3c72ecf975d9c) in polkadot-js. It's important to refactor each service to now use a `api.at()` historicApi. 

List of services to refactor:

- [X] BlocksService [#699]
- [x] AccountAssetsBalanceInfoService [#721]
- [X] AccountsBalanceInfoService [#709]
- [x] AccountsStakingInfoService [#741]
- [x] AccountsStakingPayoutsService [#762]
- [X] AccountsVestingInfoService [#709]
- [x] PalletsStakingProgressService [#761]
- [X] PalletsStorageService [#710]
- [X] ParasService [#735]
- [X] [ readjust mockApi, and historicApi for testing env [#702]

rel: [#697](https://github.com/paritytech/substrate-api-sidecar/issues/697)

**Comment by TarikGul** [comment]
Before I can go any further with this issue, [#702](https://github.com/paritytech/substrate-api-sidecar/pull/702) needs to be merged

**Comment by jacogr** [comment]
Just a note - these won't be removed anytime soon (certainly not in the mids of the 6.x range). The reality is that `api.at` is cleaner and does a whole host of things better, i.e. giving you an actual instance at that point, correctly decorated. Additionally this is used everywhere, so it certainly won't be dropped soon (probably will still live in the 7.x version as well), generally don't like breaking other people's code.

Currently the older versions now use `api.at` internally so it should yield less breakages, which with the new metadata + types is quite tricky with the (now deprecated) versions.

**Comment by TarikGul** [comment]
Okay sweet, good to know. I Appreciate the explanation. That helps a lot because I currently see some instances where I might have to leave the `api.query.*.*.at` in for the time being.  I have actually been finding `api.at` to be a really great upgrade in general as well, having the centralized source of truth in the `api` is such an incredibly useful feature.
