### ISSUE TITLE
.../blocks/head: Failed to get the latest block height

### ISSUE THREAD

**Issue by hwqwq** [paritytech/substrate-api-sidecar#727]
**Description**
substrate-api-sidecar version: v10.0.0
When I use the node I built, and the node block data has been updated synchronously, I still can't get the latest block height. But there is no problem using public nodes。

**Steps to Reproduce**
http://ip:port/blocks/head
{
    "code": 500,
    "message": "Cannot read property 'validators' of undefined",
    "stack": "TypeError: Cannot read property 'validators' of undefined\n    at BlocksService.fetchBlock (/usr/local/share/.config/yarn/global/node_modules/@substrate/api-sidecar/build/src/services/blocks/BlocksService.js:45:39)\n    at BlocksController.getLatestBlock (/usr/local/share/.config/yarn/global/node_modules/@substrate/api-sidecar/build/src/controllers/blocks/BlocksController.js:109:68)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async /usr/local/share/.config/yarn/global/node_modules/@substrate/api-sidecar/build/src/controllers/AbstractController.js:168:9",
    "level": "error"
}

**Comment by tiendq** [comment]
> Hey @hwqwq ,
> 
> When you say `node I built`, are you referring to an archive node that you are syncing? Also which chain and version are you running for the node?
> 
> If you query a node who's syncing is in progress behavior like this can happen.

I just got the same issue last Friday too. I have used sidecar with a docker based Moonbeam and it has worked well for months. There're likely some changes in Moonbeam testnet recently, and last week I switched my code to use a public Moonbeam testnet at `wss://wss.testnet.moonbeam.network` and got this same error.

**Comment by hwqwq** [comment]
@TarikGul @tiendq ,Thank you for your attention. This problem has been solved. Last time, it was caused by the error that the relay chain data was not synchronized completely because the snapshot was not used.
