### ISSUE TITLE
How do I track the success or failure of a trade after trading?

### ISSUE THREAD

**Issue by scrawld** [paritytech/substrate-api-sidecar#783]
I will get the txhash after broadcasting the transaction, but the txhash is not unique, so what is the best way to get the transaction information and make sure the transaction is successful?

Is there support for the `author_submitAndWatchExtrinsic` method?

**Comment by TarikGul** [comment]
> Is there support for the author_submitAndWatchExtrinsic method?

Currently there is no support for this, but there should be. I will work on adding it to our `/transaction/*` endpoints.

**Comment by TarikGul** [comment]
After doing a little more research and creating a small protoype, I will bring this up with the team, and see how it can fit within a RESTful application. `author_submitAndWatchExtrinsic` is not necessarily a straight forward subscription call so it will take some designing and discussion on how and if we would want to implement it.

**Comment by TarikGul** [comment]
That being said, the best way to identify your transaction, is to poll blocks, and search for the tx information, then index it. AFAIK It's not recommended to only be looking for your transaction via hash though.

**Comment by TarikGul** [comment]
Being that Sidecar is a stateless REST API, having a submitAndWatch endpoint is a little out of scope. Going to close this for now, and the draft PR i put up, as it is not ideal for the API to have. When designing Sidecar V2, we will make sure to input this sentiment.
