### ISSUE TITLE
Query support for StorageNMaps

### ISSUE THREAD

**Issue by 3yekn** [paritytech/substrate-api-sidecar#811]
**Proposed Change or Idea**

I am using a StorageNMap with 3 NMapKeys. I am able to query it from polkadot.js.org by using the parameters. I notice that the storage service only seems to support two keys. Does the sidecar api support StorageNMap?

```rust
	type DocumentID = u32;
	type ContentGroupID = Vec<u8>;
	type ContentLabel = Vec<u8>;
	type ContentValue = Vec<u8>;

	pub(super) type Documents<T> = StorageNMap<
		_, // Prefix
		(
			NMapKey<Blake2_128Concat, DocumentID>,
			NMapKey<Blake2_128Concat, ContentGroupID>,
			NMapKey<Twox64Concat, ContentLabel>,
		),
		ContentValue, // value
		ValueQuery,
	>;
```
**Alternatives**
Not yet

**Additional Information**

**Comment by TarikGul** [comment]
So currently there is no explicit support for` StorageNMap`, and you are correct that we do have support for 2 keys. I am definitely interested in adding the capability to query for it though. Will do some further research to see how we can build out the functionality.
