### ISSUE TITLE
Return code for invalid balance-info query returns HTTP status500

### ISSUE THREAD

**Issue by krutika-bisonT** [paritytech/substrate-api-sidecar#812]
**Description**

A query to `/sidecar/accounts/<account-id>/balance-info` with a non-substrate/invalid account-id returns HTTP status code 500, indicating a server error. 

**Expected vs. Actual Behavior**

Expected Behavior: The query returns code 4xx
Actual Behavior: The query returns code 500

**Proposed solution**
HTTP status code 400 (bad request) is more appropriate for incorrect input over 500 (server error).

**Comment by krutika-bisonT** [comment]
Hy @TarikGul I came across this example when a bunch of queries were placed on the endpoint with an eth address rather than a substrate address. An example query returning 500 error is `/sidecar/accounts/0x2E4d588a3dA4F9C7a14AbD63c7d68c2865A2eE88/balance-info`. A better and actionable HTTP response code here would be a 400 indicating a bad request rather than `500` indicating a more severe server error.

**Comment by TarikGul** [comment]
Ahh yes, thank you for the example. With an address, this slipped through, and ill get a fix out for it.

**Comment by krutika-bisonT** [comment]
> Ahh yes, thank you for the example. With an address, this slipped through, and ill get a fix out for it.

Thank you, @TarikGul.

**Comment by krutika-bisonT** [comment]
Thank you @TarikGul for this super quick turnaorund! Can I expect this fix to be in the next sidecar upgrade?

**Comment by TarikGul** [comment]
@krutika-bisonT Of course no worries at all. Yea so this will be in next weeks release (Most likely tuesday)!
