### ISSUE TITLE
/paras/auction/current

### ISSUE THREAD

**Issue by CrommVardek** [paritytech/substrate-api-sidecar#814]
**Description**

Version used : 11.3.5 (running on a Docker container)

When accessing /paras/auctions/current?at=10935634 the response is
` {"at":{"hash":"0xf131bf645d5860b103c7aa1e00866a78a2b1890c35bb90e395c3b43951d43970","height":"10935634"},"beginEnd":"10914000","finishEnd":"10986000","phase":"endPeriod","auctionIndex":"21","leasePeriods":["19","20","21","22","23","24","25","26"],"winning":null} `

However there is a winning bidder (with the paraId 2015), so I was not expecting a null value for that field in the response. But rather some object as described in the doc : 

`
  "winning": [
    {
      "bid": {
        "accountId": "string",
        "paraId": "string",
        "amount": "string"
      },
      "leaseSet": [
        "string"
      ]
    }
  ]`

**Steps to Reproduce**

Run substrate-api-sidecar on docker

Access /paras/auctions/current?at=10935634 url (or with no parameter, or any parameter which is a block that was created during any auction) 

**Expected vs. Actual Behavior**

See Description section.

**Comment by TarikGul** [comment]
Hey @CrommVardek, thanks for reporting this, I am looking into it.

**Comment by TarikGul** [comment]
Hey @CrommVardek, just a heads up I am giving this my full attention again tomorrow.

**Comment by CrommVardek** [comment]
Thanks @TarikGul !

**Comment by TarikGul** [comment]
Okay, so after doing some much needed digging, I have found the overall source of the problem, I just need to get proper fix in which I am still working on. 

But the correct response should look something like this for the current auction in kusama for example:

```
{
	"at": {
		"hash": "0x19d2731e12b15bb1e990b300c5034d7a0f66be685980d9f389257ddd2c76c2ee",
		"height": "11048276"
	},
	"beginEnd": "11014800",
	"finishEnd": "11086800",
	"phase": "endPeriod",
	"auctionIndex": "22",
	"leasePeriods": [
		"19",
		"20",
		"21",
		"22",
		"23",
		"24",
		"25",
		"26"
	],
	"winning": [
		......
		{
			"bid": null,
			"leaseSet": [
				"19",
				"20",
				"21",
				"22",
				"23",
				"24",
				"25"
			]
		},
		{
			"bid": {
				"accountId": "F3opxRbN5ZZRfqouub1bWp7jLHs5NcgZrdixY1nkXYvZAmL",
				"paraId": "2105",
				"amount": "6267478226000000"
			},
			"leaseSet": [
				"19",
				"20",
				"21",
				"22",
				"23",
				"24",
				"25",
				"26"
			]
		},
		{
			"bid": null,
			"leaseSet": [
				"20"
			]
		},
		{
			"bid": null,
			"leaseSet": [
				"20",
				"21"
			]
		},
		{
			"bid": null,
			"leaseSet": [
				"20",
				"21",
				"22"
			]
		},
                ....
	]
}
```

**Comment by CrommVardek** [comment]
Hey, thanks for the update, indeed, that was the response's model I used to get before I upgraded to the last version.

**Comment by TarikGul** [comment]
@CrommVardek The fix is officially in master, the release will be Wednesday. Thanks again for reporting this!

**Comment by CrommVardek** [comment]
Thanks @TarikGul !
