### ISSUE TITLE
Get block 0

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/substrate-api-sidecar#82]
Right now we are querying some fee params on `parentHash`, but of course it can't get them for block 0 because the parent is hardcoded `0x000...000`. But there are no txs in block 0, so we should only do fee calculation if `blockNumber > 0`.

**Comment by danforbes** [comment]
FYI I have this staged https://github.com/paritytech/substrate-api-sidecar/compare/fix/block/genesis
