### ISSUE TITLE
v11.3.8 not parse call parameters

### ISSUE THREAD

**Issue by jqriyv** [paritytech/substrate-api-sidecar#835]
v11.3.8 return block info, not parse call parameters
![image](https://user-images.githubusercontent.com/5435244/152631253-a923d2a7-6202-4de1-b50c-f236f97b58e9.png)
This is the return information of the previous version
![image](https://user-images.githubusercontent.com/5435244/152631289-a881b1c7-2640-4383-9f40-d51207af77f5.png)
Mind if you can parse all call parameters, such as proposal preimage

**Comment by TarikGul** [comment]
hey @jqriyv, thanks for reporting this. Can you provide a reproducible example so I can check this specific example, and hopefully get a patch out for this.

I would need:
1. The chain you are connected to,
2. the query you are making

**Comment by jqriyv** [comment]
1. the chain is polkadot.
2. http://xxxxx/blocks/8891183

**Comment by TarikGul** [comment]
Thanks again, I was able to reproduce it. Now just seeing how it was affected upstream.

**Comment by jqriyv** [comment]
OK, I hope it can be repaired as soon as possible. This affects me, Thanks

**Comment by TarikGul** [comment]
Yea this is a tricky one to debug because the parsing of the calls is a little complex, but I am working on getting this resolved, and am hoping to get a solution out for next weeks release.

**Comment by TarikGul** [comment]
Ahhhh, i think i found the root of the problem :)
