### ISSUE TITLE
Please release the docker image in time, several versions have not been released

### ISSUE THREAD

**Issue by vae520283995** [paritytech/substrate-api-sidecar#854]
The latest version released by github is v11.3.11, but docker is still v11.3.9
@TarikGul

**Comment by TarikGul** [comment]
Thanks for filing the issue. It's being worked on as we speak

**Comment by niklasad1** [comment]
@TarikGul can we integrate it in the release process somehow or does it need manual work?

**Comment by TarikGul** [comment]
@vae520283995 Via [#855](https://github.com/paritytech/substrate-api-sidecar/pull/855) it is now resolved. Going to do a patch release, 11.3.12 which will have the updated docker release. It will be exactly the same as 11.3.11 but with the CI patch.

**Comment by vae520283995** [comment]
> @vae520283995 Via [#855](https://github.com/paritytech/substrate-api-sidecar/pull/855) it is now resolved. Going to do a patch release, 11.3.12 which will have the updated docker release. It will be exactly the same as 11.3.11 but with the CI patch.

That's great

**Comment by TarikGul** [comment]
Fixed. Closing, feel free to reopen, or file a new issue if you see anything else. Thanks again for filing the issue.
