### ISSUE TITLE
`trace` endpoints are not available in the "Substrate API Sidecar" page

### ISSUE THREAD

**Issue by Imod7** [paritytech/substrate-api-sidecar#866]
### Description

When I open the link "_Click here for full endpoint docs_" from the [README](https://github.com/paritytech/substrate-api-sidecar#finishing-up), I am forwarded in this [page](https://paritytech.github.io/substrate-api-sidecar/dist/) where I can see all the available endpoints. In this list of endpoints I can also see the following `trace` related endpoints:
```
/experimental/blocks/head/traces
/experimental/blocks/{blockId}/traces
/experimental/blocks/head/traces/operations
/experimental/blocks/{blockId}/traces/operations
```

However, when I run a dev node locally, I also run the last version of sidecar and then open the sidecar link [http://127.0.0.1:8080/](http://127.0.0.1:8080/), I cannot find these `trace` related endpoints.  

### Steps to Reproduce
- I run a polkadot dev node with the following command : `./target/release/polkadot --dev --tmp`
- Some of the logs when I run my local node : 
```
2022-03-08 15:58:22 Parity Polkadot
2022-03-08 15:58:22 ✌️  version 0.9.17-9907414f50-x86_64-macos
2022-03-08 15:58:22 ❤️  by Parity Technologies <admin@parity.io>, 2017-2022
2022-03-08 15:58:22 📋 Chain specification: Development
2022-03-08 15:58:22 🏷  Node name: pathetic-current-9901
2022-03-08 15:58:22 👤 Role: AUTHORITY
2022-03-08 15:58:22 💾 Database: RocksDb at /var/folders/0_/jshy381x5f3f115gg_q0vh7c0000gn/T/substrate7QLkUN/chains/dev/db/full
2022-03-08 15:58:22 ⛓  Native runtime: polkadot-9170 (parity-polkadot-0.tx11.au0)
```
- Then I also run sidecar locally and its logs are the following : 
```
SAS:
  📦 LOG:
     ✅ LEVEL: "info"
     ✅ JSON: false
     ✅ FILTER_RPC: false
     ✅ STRIP_ANSI: false
  📦 SUBSTRATE:
     ✅ WS_URL: "ws://127.0.0.1:9944"
     ✅ TYPES_BUNDLE: undefined
     ✅ TYPES_CHAIN: undefined
     ✅ TYPES_SPEC: undefined
     ✅ TYPES: undefined
  📦 EXPRESS:
     ✅ BIND_HOST: "127.0.0.1"
     ✅ PORT: 8080
2022-03-08 16:00:59 info: Version: 11.3.12
2022-03-08 16:01:00 info: Connected to chain Development on the parity-polkadot client at ws://127.0.0.1:9944
2022-03-08 16:01:00 info: Listening on http://127.0.0.1:8080/
2022-03-08 16:01:00 info: Check the root endpoint (http://127.0.0.1:8080/) to see the available endpoints for the current node
```
- Then I open the link http://127.0.0.1:8080/ to check the `trace` endpoints and that is when I realize the discrepancy.

### Expected vs. Actual Behavior
I thought that the endpoints that are documented in [Substrate API Sidecar](https://paritytech.github.io/substrate-api-sidecar/dist/) page would be the same with the endpoints that I find locally in the page [http://127.0.0.1:8080/](http://127.0.0.1:8080/) but they are not. Maybe it is related with the fact that these endpoints are `experimental` ?

### Ideas to resolve the issue 
Maybe the page [Substrate API Sidecar](https://paritytech.github.io/substrate-api-sidecar/dist/) should be updated ?
I saw that the `trace` endpoints are mentioned in the file [openapi-v1.yaml](https://github.com/paritytech/substrate-api-sidecar/blob/master/docs/src/openapi-v1.yaml) and they start in this [line](https://github.com/paritytech/substrate-api-sidecar/blob/f0eeda31ae0f45181a8238fbedc89c53e048f6b9/docs/src/openapi-v1.yaml#L1167) so maybe if we delete those lines that refer to the `trace` endpoints, then the "Substrate API Sidecar" page would be updated ? I also found this file [openapi-v1-todo.yaml](https://github.com/paritytech/substrate-api-sidecar/blob/master/docs/src/openapi-v1-todo.yaml) where the `trace` endpoints are not mentioned so maybe this file is also related ?

**Comment by TarikGul** [comment]
When running your polkadot node it needs to be run with the `--unsafe-rpc-external` flag in order to access the rpc endpoints it utilizes. 

For your case with polkadot, currently `BlocksTrace` controller is only activated for Kusama. So you would need to run a kusama dev node to see those endpoints `./target/release/polkadot --chain=kusama-dev --tmp --force-kusama=authoring --rpc-cors=all --alice`

**Comment by TarikGul** [comment]
These are all the active controllers for [Polkadot](https://github.com/paritytech/substrate-api-sidecar/blob/master/src/chains-config/polkadotControllers.ts).

These are all the active controllers for [Kusama](https://github.com/paritytech/substrate-api-sidecar/blob/master/src/chains-config/kusamaControllers.ts). You'll notice that `BlocksTrace` is only active for kusama.
