### ISSUE TITLE
start error

### ISSUE THREAD

**Issue by leezijie** [paritytech/substrate-api-sidecar#867]
**Description**

I followed the steps to install the latest version 11.3.13,environment variables are also configured and started kusama's service.
Everything looks fine, but the startup prompts an error.

Like this.
![image](https://user-images.githubusercontent.com/32590143/157615681-df0be4ca-409d-4161-92b2-0a0a2ed8a677.png)

**Comment by TarikGul** [comment]
Hey @leezijie, what version of kusama are you running locally?

**Comment by leezijie** [comment]
> Hey @leezijie, what version of kusama are you running locally?

Hi @TarikGul , latest release version, v0.9.17.

**Comment by leezijie** [comment]
> > Hey @leezijie, what version of kusama are you running locally?
> 
> Hi @TarikGul , latest release version, v0.9.17.

Just now I started the service again and it is no problem.Need to wait for the completion of block synchronization. Thank you anyway
