### ISSUE TITLE
Error response loading Westend blocks between 328249 and 392764 inclusive

### ISSUE THREAD

**Issue by mcalcanot0** [paritytech/substrate-api-sidecar#880]
**Description**

This bug seems to be the same as https://github.com/paritytech/substrate-api-sidecar/issues/329 but when hitting the GET http://localhost:8080/blocks/{blockNumber} endpoint

**Steps to Reproduce**

Run `docker run --rm -it --read-only -p 8080:8080 -e SAS_SUBSTRATE_WS_URL=wss://[westend-rpc.polkadot.io](http://westend-rpc.polkadot.io/) -e SAS_LOG_LEVEL=debug parity
[logs.log](https://github.com/paritytech/substrate-api-sidecar/files/8358284/logs.log)
/substrate-api-sidecar:latest`

Try to load any blocks between 328249 and 392764 by loading in your browser their URL `http://localhost:8080/blocks/328249`

Receive and error response instead of the blocks contents: `{
  "code": 500,
  "message": "Cannot read property 'extrinsicBaseWeight' of undefined",
  "stack": "TypeError: Cannot read property 'extrinsicBaseWeight' of undefined\n at BlocksService.createCalcFee (/usr/src/app/build/src/services/blocks/BlocksService.js:343:69)\n at processTicksAndRejections (node:internal/process/task_queues:94:5)\n at async BlocksService.fetchBlock (/usr/src/app/build/src/services/blocks/BlocksService.js:91:35)\n at async BlocksController.getBlockById (/usr/src/app/build/src/controllers/blocks/BlocksController.js:134
[logs.log](https://github.com/paritytech/substrate-api-sidecar/files/8358286/logs.log)
:49)\n at async /usr/src/app/build/src/controllers/AbstractController.js:168:9",
  "level": "error"
}`

See attached logs as well.

[logs.log](https://github.com/paritytech/substrate-api-sidecar/files/8358293/logs.log)

**Expected vs. Actual Behavior**

Expected to be able to load block information for blocks between 328249 and 392764 inclusive, instead got an error response.

**Comment by TarikGul** [comment]
Hey @mcalcanot0, so I am not able to reproduce the said above issue I checked on v11.3.14, and iterated through each block above, and none failed. Im not quite to sure why the 'extrinsicBaseWeight' issue is coming up for you meaning its having trouble handling partialFee calculation.

**Comment by mcalcanot0** [comment]
Thanks for looking at this @TarikGul ! I can confirm this somehow works now. Kinda fascinating that it was not working before, maybe the source of the problem was upstream, i.e. in the response from wss://[westend-rpc.polkadot.io. or perhaps something else entirely...
