### ISSUE TITLE
Staking "Bonded" undefined

### ISSUE THREAD

**Issue by UsamaSultan** [paritytech/substrate-api-sidecar#881]
While requesting a GLMR address for staking-info , Getting a response of 500 internal server error as 

{"code":500,"message":"Cannot read properties of undefined (reading 'bonded')","stack":"TypeError: Cannot read properties of undefined (reading 'bonded')\n    at AccountsStakingInfoService.fetchAccountStakingInfo (/usr/local/substrate-api-sidecar-11.3.14/build/src/services/accounts/AccountsStakingInfoService.js:18:39)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async AccountsStakingInfoController.getAccountStakingInfo (/usr/local/substrate-api-sidecar-11.3.14/build/src/controllers/accounts/AccountsStakingInfoController.js:61:62)\n    at async /usr/local/substrate-api-sidecar-11.3.14/build/src/controllers/AbstractController.js:168:9","level":"error"}

URL used: */sidecar/accounts/0xFc1084962DE75E1480bbbb5a0909fE8e1498977d/staking-info

**Comment by TarikGul** [comment]
Thanks for reporting this, checking it out. What kind of node were you querying against? (Assuming this was a moonbeam node)?

**Comment by TarikGul** [comment]
Also the runtime version you are querying against would be helpful as well.

**Comment by UsamaSultan** [comment]
Yes it is moon beam node

moonbeam fullnode (RPC node): moonbeam 0.21.1-bd3048299-x86_64-linux-gnu

substrate-api-sidecar: 11.3.14

**Comment by TarikGul** [comment]
Just to confirm as well, I am able to reproduce the issue:

What I am currently seeing is that there is no staking pallet available to query. Therefore it's failing to on [this line](https://github.com/paritytech/substrate-api-sidecar/blob/master/src/services/accounts/AccountsStakingInfoService.ts#L23). 

I believe in this case it's just parachainStaking instead. Which is a really good catch. 
```
[
  'substrate',
  'system',
  'parachainSystem',
  'randomnessCollectiveFlip',
  'timestamp',
  'parachainInfo',
  'balances',
  'transactionPayment',
  'parachainStaking',
  'authorInherent',
  'authorFilter',
  'authorMapping',
  'proxy',
  'maintenanceMode',
  'identity',
  'migrations',
  'ethereumChainId',
  'evm',
  'ethereum',
  'baseFee',
  'scheduler',
  'democracy',
  'councilCollective',
  'techCommitteeCollective',
  'treasury',
  'crowdloanRewards',
  'xcmpQueue',
  'dmpQueue',
  'polkadotXcm',
  'assets',
  'assetManager',
  'xTokens',
  'xcmTransactor'
]
```

**Comment by UsamaSultan** [comment]
Ok, So you mean there will be a chain configuration for moonbeam here  ??
https://github.com/paritytech/substrate-api-sidecar/tree/master/src/chains-config

**Comment by TarikGul** [comment]
So there currently is none, which means it's using the defaultController. We don't maintain the controller configs for external chains. PR's are most definitely welcome.

A controllers config would not completely solve the issue here. What it can do is block those controllers from being accessible upon initialization of the server.  What would really need to happen is a controller would need to be built out for ParachainsStaking that leverages the API available when constructed in polkadot.js/api. But it would also need to cater to their staking logic as well, as I am not familiar with it.

**Comment by TarikGul** [comment]
Closing in favor of https://github.com/paritytech/substrate-api-sidecar/issues/886
