### ISSUE TITLE
Unable to decode storage session.validators

### ISSUE THREAD

**Issue by lcovar** [paritytech/substrate-api-sidecar#898]
Description

Polkadot v0.9.18
substrate-api-sidecar v11.3.16

Steps to Reproduce
curl /blocks/10480973

logs:
{"code":500,"message":"Unable to decode storage session.validators:: createType(Vec<PalletAuthorshipUncleEntryItem>):: decodeU8a: failed at 0x15aca2d56792295e3366b37371876a48…: {\"_enum\":{\"InclusionHeight\":\"u32\",\"Uncle\":\"(H256,Option<AccountId32>)\"}}:: Unable to create Enum via index 21, in InclusionHeight, Uncle","stack":"Error: Unable to decode storage session.validators:: createType(Vec<PalletAuthorshipUncleEntryItem>):: decodeU8a: failed at 0x15aca2d56792295e3366b37371876a48…: {\"_enum\":{\"InclusionHeight\":\"u32\",\"Uncle\":\"(H256,Option<AccountId32>)\"}}:: Unable to create Enum via index 21, in InclusionHeight, Uncle\n    at RpcCore._newType (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:477:13)\n    at RpcCore._formatStorageData (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:423:17)\n    at RpcCore._formatOutput (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:397:19)\n    at RpcCore._formatResult (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:222:27)\n    at callWithRegistry (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:250:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","level":"error"}I have no name!@dot-fullnode-1:/bin$

**Comment by lcovar** [comment]
Restarting the node fixed this.

**Comment by rootmout** [comment]
I got the same issue on my side with latest version `@substrate/api-sidecar v12.4.3`
```
rpc error (500): Unable to decode storage session.validators:: createType(PalletDemocracyEvent):: 
Unable to create Enum via index 165, in Proposed, Tabled, ExternalTabled, Started, Passed, NotPassed,
Cancelled, Executed, Delegated, Undelegated, Vetoed, PreimageNoted, PreimageUsed, PreimageInvalid,
PreimageMissing, PreimageReaped, Blacklisted, Voted, Seconded
```

Do you have any idea what can cause this error? 
A reboot is effectively working but the problem reappears regularly and it's a bit annoying :/

I already monitor `/blocks/head/header` but this endpoint can still alive while `/blocks/<random_block_id>` returns the above error. Monitor this last endpoint is pretty complicated due to the number of combinations...

**Comment by TarikGul** [comment]
@rootmout 

- Do you have a specific block this is happening at so I can reproduce and see why there is a session.validators issue? 
- What kind of node are you querying? Is this a full-node, or archive node?
- What chain is this for?

**Comment by rootmout** [comment]
Hi @TarikGul 

> Do you have a specific block this is happening at so I can reproduce and see why there is a session.validators issue?

it's happen on block `10156852` with hash `0x6dee263a06c5e658a71242d82505778b4cf26c5a20ef368e1eaf7b9918aa7ab9` I know that the block is old but next time it occurs I will inform you immediately. Note that, like @lcovar, a restart fix the issue so I suppose it isn't reproducible. 

> What kind of node are you querying? Is this a full-node, or archive node?

regular node (no archive, no validator) 

> What chain is this for?

DOT mainnet

**Comment by PizBernina** [comment]
I can see this error now on the public kusama sidecar node:
https://kusama-public-sidecar.parity-chains.parity.io/blocks/16351695
KSM mainnet
version: "14.1.2"

```
{
code: 500,
message: "Unable to decode storage session.validators:: createType(Percent):: Percent:: Decoded input doesn't match input, received 0xa10f0000966d74f8027e07b43717b6876d97544fe0d71facef06acc8382749ae…fefcf5c5ceafd47ef731146baa24e4972f0914dc19c4745098c4ea62e9f87456 (32002 bytes), created 0xa1 (1 bytes)",
stack: "Error: Unable to decode storage session.validators:: createType(Percent):: Percent:: Decoded input doesn't match input, received 0xa10f0000966d74f8027e07b43717b6876d97544fe0d71facef06acc8382749ae…fefcf5c5ceafd47ef731146baa24e4972f0914dc19c4745098c4ea62e9f87456 (32002 bytes), created 0xa1 (1 bytes)
    at RpcCore._newType (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:454:13)
    at RpcCore._formatStorageData (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:391:17)
    at RpcCore._formatOutput (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:365:19)
    at RpcCore._formatResult (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:209:27)
    at callWithRegistry (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:235:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
level: "error"
}
```

**Comment by TarikGul** [comment]
> Weirdly enough, I still get it on my private node for specific blocks but not always. So, I just query said specific block again and it works (after I restarted it, before it did not work at all).

Yea it definitely is weird, we haven't been able to identify why it happens for a while now, but hopefully we get there soon. Either way it will be fixed fully in the future, either from identifying the bug, or with our new rework of Sidecar coming out by the end of the year it will be resolved.
