### ISSUE TITLE
yarn test:init-e2e-tests return Error: spawn yarn ENOENT

### ISSUE THREAD

**Issue by lanmeng656** [paritytech/substrate-api-sidecar#964]
![微信截图_20220616105940](https://user-images.githubusercontent.com/17455710/173981806-8b34b409-4ef3-412d-b412-d2833aa6d8c2.png)

**Comment by niklasad1** [comment]
Hey,

Did you run `$ yarn && yarn test:init-e2e-tests`?

**Comment by TarikGul** [comment]
Closing this issue due to being stale. All e2e scripts are working myself, and those who help release sidecar. Please reopen with a reproduction repo if you see further issues.
