### ISSUE TITLE
Mismatched fee amount for Acala

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate-api-sidecar#969]
Reported by an exchange. For this transaction: https://acala.subscan.io/extrinsic/0x31d946cd2e6939d394d9160383e552a3c46a38fb8b7cb5e8e2c96d089e531990

The fee from sidecar is `2490128142` but the actual fee is `2490128143`

**Comment by TarikGul** [comment]
Hey so I just queried the block and noticed the difference as well. The on chain data for each event shows the correct partialFee too:

```
...
				{
					"method": {
						"pallet": "treasury",
						"method": "Deposit"
					},
					"data": [
						"2490128143"
					]
				},
...
```

So to be clear the fee calculations are being done via rpc as can be seen [here](https://github.com/paritytech/substrate-api-sidecar/blob/master/src/services/blocks/BlocksService.ts#L246-L247). We no longer calculate partialFees ourselves. That being said I will prioritize tomorrow (Its 1am for me :) giving a query param to allow retrieving the fee from the event data. It's on the roadmap given this issue from the past https://github.com/paritytech/substrate-api-sidecar/issues/756 but I'll get it done as this is now an option that should be given and it'll resolve this mismatch.

**Comment by IkerAlus** [comment]
Just to add to this topic Houbi is reporting similar issues. They provided this two transactions as example:

https://shiden.subscan.io/extrinsic/0xbb4ab65eb0fd8cb6b1c713a4749475af4c0cbac04a334fb949980632989d2afe

- sidecar fee: 1611916810109184
- subscan fee: 1611916814889018

and

https://shiden.subscan.io/extrinsic/0xd137935c98e5eb914cdb0169669bfb8c3cb718144b05021671ac06c282522bf9

- sidecar fee: 1611917524103649
- subscan fee: 1611917528885264

**Comment by LXHLeaner** [comment]
Has this issue been resolved?

https://acala-testnet.subscan.io/extrinsic/0xa3407f024852241ce18e3eeb08b7d2a7a95b22ef6db001a52b29e9e53130777d
sidecar fee: 15631412694
subscan fee: 15631412773

**Comment by vae520283995** [comment]
@TarikGul 
v12.4.0 has two problems
1: Once feeByEvent is set to true or false, if you want to modify it, you must restart
2: If the transaction contains a tip, resulting in a difference greater than 00.00001, an error will be returned
```
"tip": "5729827274000",
            "hash": "0x5cbf55d87cf82e5272e7ce2237a81f673b203fdfe428d7d2531406f3eecff747",
            "info": {
                "error": "Could not find a reliable fee within the events data."
            }
```

**Comment by TarikGul** [comment]
@vae520283995 Thanks for reporting the issue. 

Can you give me a chain, and a specific block to work with to get this resolved. Thanks again.

**Comment by vae520283995** [comment]
> @vae520283995 Thanks for reporting the issue.
> 
> Can you give me a chain, and a specific block to work with to get this resolved. Thanks again.

https://astar.subscan.io/extrinsic/1431734-2

**Comment by LXHLeaner** [comment]
when i put "getFeeByEvent:=true", i find i get the fee is only a estimate fee but not the actual fee, when i syncer the block  at karura chain  or centifuge chain?

**Comment by TarikGul** [comment]
@LXHLeaner The query param is `feeByEvent?=true`

**Comment by TarikGul** [comment]
@vae520283995 So https://github.com/paritytech/substrate-api-sidecar/pull/986 fixes the issue you presented. Thanks for reporting it, once that goes into master, a release will be put out shortly after.

**Comment by vae520283995** [comment]
@TarikGul Why is partialFee = actual fee, the actual fee should be = partialFee + tip

**Comment by TarikGul** [comment]
@vae520283995 You are referencing `feeByEvent` right?

**Comment by vae520283995** [comment]
> @vae520283995 You are referencing `feeByEvent` right?

yes

**Comment by TarikGul** [comment]
> > @vae520283995 You are referencing `feeByEvent` right?
> 
> yes, Fees will not match if feeByEvent is not referenced

Ahh Okay, so the code itself takes into account the tip when searching for the event (because the event includes the tip), but sidecar just returns whats in the event. It needs to technically subtract the tip from the event data in order to have a correct partialFee, which is what needs to be fixed. 

Thanks for this catch. Lots of little nuances with fees...

**Comment by vae520283995** [comment]
> Ahh Okay, so the code itself takes into account the tip when searching for the event (because the event includes the tip), but sidecar just returns whats in the event. It needs to technically subtract the tip from the event data in order to have a correct partialFee, which is what needs to be fixed.

Will this be fixed in the next version?

**Comment by TarikGul** [comment]
Yup, ill get it out a fix before we release.

**Comment by vae520283995** [comment]
@TarikGul Kusama network https://kusama.subscan.io/extrinsic/0xa7c0aa44dcadaaedc9680507d2671d3a2a60131238aa5f6901e07a82f80cf4cb
?feeByEvent=true
```
"tip": "0",
            "hash": "0xa7c0aa44dcadaaedc9680507d2671d3a2a60131238aa5f6901e07a82f80cf4cb",
            "info": {
                "error": "Could not find a reliable fee within the events data."
            },
```

?feeByEvent=false
```
"tip": "0",
            "hash": "0xa7c0aa44dcadaaedc9680507d2671d3a2a60131238aa5f6901e07a82f80cf4cb",
            "info": {
                "weight": "18403891000",
                "class": "Normal",
                "partialFee": "979621076"
            },
```

**Comment by TarikGul** [comment]
@vae520283995 For kusama you shouldn't have to use `feeByEvent` the query param is parachain focused.
