### ISSUE TITLE
get Shiden 1500094 fee failed

### ISSUE THREAD

**Issue by LXHLeaner** [paritytech/substrate-api-sidecar#989]
get the dataArr[0] is WuSTANhkhikbhfsifpeTW3dHvb4UotErkCCs7sLxxGfg57z
get the dataArr[1] is 0x000000000000000000119e2433bf11f3.

and new BN(fee) is err 

// The difference between values is 00.00001% or less so they are alike.
				if (this.areFeesSimilar(new BN(fee), partialFee)) {
					return {
						partialFee: fee.toString(),
					};
				}

**Comment by LXHLeaner** [comment]
It is  have problem. at height: 1500099

private sanitizeFee(fee: string): string {
		if (isHex(fee)) {
			const numFee = hexToNumber(fee);
			return numFee.toString(10);
		}

		return fee;
	}

input: 
fee = 0x00000000000000000025aa5276c6653d

output:
2022-07-29 14:56:43 info: WAyw2mtxkRk9vjmwBdGivFduhVmGEeCH8JAXVmREzku92a8
2022-07-29 14:57:07 error: getTxList Error: Number can only safely store up to 53 bits

**Comment by TarikGul** [comment]
@LXHLeaner Thanks for bringing this up, will get a fix out.
