### ISSUE TITLE
Hi! I am new to ethereum can you please advice how to do 50,000 transactions on private etheruem and analyze the throughput

### ISSUE THREAD

**Issue by IqraSA** [paritytech/substrate-api-sidecar#991]
**Proposed Change or Idea**

[Describe your request for a new idea/feature or improvement of an existing
feature.]

**Alternatives**

[Are there alternative approaches or solutions that you’ve considered?]

**Additional Information**

[Add any other details about the feature request here.]

**Comment by jsdw** [comment]
This project is for Substrate based nodes/chains such as Polkadot and Kusama, not Ethereum :)
